import { GoogleGenAI } from '@google/genai';
import { Resource, ColorCategory, AISettings } from '../types';

// Default Gemini client (fallback if no custom settings)
const defaultAi = new GoogleGenAI({ apiKey: process.env.GEMINI_API_KEY });

export interface GenerateChunkParams {
  resources: Resource[];
  rTotal: number;
  iValue: number;
  uTotal: number;
  theme?: string;
  sentenceLength?: 'Short' | 'Medium' | 'Long';
  settings?: AISettings;
}

export interface GeneratedChunkResponse {
  engSentence: string;
  vieSentence: string;
  category: string;
}

export interface AutoGenerateParams {
  theme: string;
  targetU: number;
  quantity: number;
  sentenceLength: 'Short' | 'Medium' | 'Long';
  colorPreferences: ColorCategory[];
  availableResources: Resource[];
  settings?: AISettings;
}

export interface AutoGeneratedChunk extends GeneratedChunkResponse {
  resourcesUsed: Resource[];
  rTotal: number;
  iValue: number;
  uTotal: number;
  difficultyLabel: string;
  audioUrl?: string | null;
}

export interface SemanticChunk {
  text: string;
  label: 'GREEN' | 'BLUE' | 'RED' | 'PINK' | 'NONE';
  ohm: number;
  confidence: number;
  reason: string;
}

export interface OhmAnalysisResult {
  transcriptRaw: string;
  transcriptNormalized: string;
  chunks: SemanticChunk[];
  formula: string;
  totalOhm: number;
}

export async function transcribeAudio(audioBlob: Blob): Promise<string> {
  const base64Audio = await new Promise<string>((resolve, reject) => {
    const reader = new FileReader();
    reader.onloadend = () => {
      const base64 = (reader.result as string).split(',')[1];
      resolve(base64);
    };
    reader.onerror = reject;
    reader.readAsDataURL(audioBlob);
  });

  const response = await defaultAi.models.generateContent({
    model: 'gemini-2.5-flash',
    contents: [
      {
        inlineData: {
          mimeType: audioBlob.type || 'audio/webm',
          data: base64Audio
        }
      },
      "Please transcribe this audio. Return ONLY the transcript text in the language spoken, with no other commentary, quotes, or formatting."
    ]
  });
  return response.text ? response.text.trim() : '';
}

export async function analyzeTranscript(transcript: string, settings?: AISettings, baseOhms?: Record<string, number>): Promise<OhmAnalysisResult> {
  const ohms = baseOhms || { Green: 5, Blue: 7, Red: 9, Pink: 3 };
  
  const prompt = `
You are an expert linguistic analyzer. Analyze the following transcript and extract semantic chunks based on these 4 categories:
- GREEN (${ohms.Green} Ohm): Gap fillers, discourse markers, transition phrases, openers (e.g., "Từ bây giờ", "Nói cách khác", "Thành thật mà nói").
- BLUE (${ohms.Blue} Ohm): Sentence frames, reusable communication templates. These are typically INCOMPLETE sentence starters or grammatical structures waiting for a payload (e.g., "Cậu nên nhớ rằng...", "Nếu cậu mà biết nghĩ thì cậu đâu có...", "Tui không hiểu cậu lấy đâu ra... để..."). DO NOT classify complete, standalone factual sentences as BLUE.
- RED (${ohms.Red} Ohm): Idiomatic expressions, figurative language, vivid colloquial sayings (e.g., "mọi thứ đều có cái giá của nó", "chuyện nhỏ").
- PINK (${ohms.Pink} Ohm): Key terms, specific concepts, lexical topic units (e.g., "ví điện tử", "công nghệ").

CRITICAL RULES FOR CHUNKING:
1. DO NOT classify every word or sentence. Most of the transcript is just normal speech and MUST BE IGNORED.
2. BLUE IS NOT A CATCH-ALL: Do not put leftover or normal sentences into BLUE. A regular statement (e.g., "Hôm nay trời mưa", "Tôi đang đi làm") is NOT BLUE. BLUE must be a specific, reusable template.
3. Common verbs (e.g., "bơi", "ăn"), common nouns (e.g., "mưa", "ngày"), or basic adjectives are NOT PINK unless they are highly specific technical jargon.
4. Do not force a classification. If a sentence only has one BLUE frame and the rest is normal speech, ONLY extract the BLUE frame and ignore the rest.
5. Extract exact substrings from the transcript.
6. Provide a brief reason for the classification.
7. Estimate a confidence score between 0.0 and 1.0.

Rules for Ohm calculation:
- GREEN = ${ohms.Green}, BLUE = ${ohms.Blue}, RED = ${ohms.Red}, PINK = ${ohms.Pink}.
- If multiple chunks have the SAME label, ADD their values.
- If chunks have DIFFERENT labels, MULTIPLY the group sums.
Example 1: 1 GREEN, 1 BLUE -> ${ohms.Green} * ${ohms.Blue} = ${ohms.Green * ohms.Blue}
Example 2: 2 GREENs, 1 RED -> (${ohms.Green} + ${ohms.Green}) * ${ohms.Red} = ${(ohms.Green + ohms.Green) * ohms.Red}
Example 3: 1 RED, 2 PINKs -> ${ohms.Red} * (${ohms.Pink} + ${ohms.Pink}) = ${ohms.Red * (ohms.Pink + ohms.Pink)}

Transcript:
"${transcript}"

Return the result STRICTLY as a JSON object with this structure:
{
  "transcriptRaw": "original transcript",
  "transcriptNormalized": "lowercase, no punctuation version of transcript",
  "chunks": [
    {
      "text": "extracted text",
      "label": "GREEN|BLUE|RED|PINK",
      "ohm": number,
      "confidence": number,
      "reason": "short reason"
    }
  ],
  "formula": "string representing the math formula (e.g., '5 x 7 x 3' or '(5 + 5) x 9')",
  "totalOhm": number
}
`;

  const responseText = await callAI(prompt, settings);
  try {
    const jsonMatch = responseText.match(/```json\n([\s\S]*?)\n```/) || responseText.match(/\{[\s\S]*\}/);
    const jsonString = jsonMatch ? (jsonMatch[1] || jsonMatch[0]) : responseText;
    const result = JSON.parse(jsonString) as OhmAnalysisResult;
    return result;
  } catch (error) {
    console.error("Failed to parse analysis result:", responseText);
    throw new Error("Failed to parse analysis result from AI.");
  }
}

export async function fetchOpenRouterModels(apiKey: string, endpoint: string = 'https://openrouter.ai/api/v1') {
  if (!apiKey) return [];
  try {
    const response = await fetch(`/api/ai/models?endpoint=${encodeURIComponent(endpoint)}`, {
      method: 'GET',
      headers: {
        'Authorization': `Bearer ${apiKey}`,
      },
    });
    if (!response.ok) throw new Error(`Failed to fetch models: ${response.statusText}`);
    const data = await response.json();
    return data.data || [];
  } catch (error) {
    console.error('Error fetching models:', error);
    throw error;
  }
}

async function callAI(prompt: string, settings?: AISettings): Promise<string> {
  if (!settings || !settings.apiKey) {
    // Use default Gemini
    const response = await defaultAi.models.generateContent({
      model: 'gemini-2.0-flash',
      contents: prompt,
    });
    if (!response.text) throw new Error("No response from Gemini");
    return response.text;
  }

  const { endpoint, apiKey, primaryModel, fallbackModel } = settings;
  const modelsToTry = [primaryModel, fallbackModel].filter(Boolean);
  let lastError = null;

  for (const model of modelsToTry) {
    try {
      const response = await fetch('/api/ai/chat', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          'Authorization': `Bearer ${apiKey}`,
        },
        body: JSON.stringify({
          endpoint,
          model: model,
          messages: [{ role: 'user', content: prompt }],
        }),
      });

      if (!response.ok) {
        const errorData = await response.json().catch(() => ({}));
        let errorMessage = errorData.error?.message || errorData.error || errorData.message;
        
        if (!errorMessage && errorData.rawResponse) {
          // Extract text from HTML if it's a Cloudflare error page
          const raw = errorData.rawResponse;
          if (raw.includes('<html') && raw.includes('530')) {
            errorMessage = 'API Error 530: Cloudflare DNS/Origin error. The AI endpoint might be down or misconfigured.';
          } else {
            errorMessage = `API Error ${response.status}: ${raw.substring(0, 100)}...`;
          }
        }
        
        errorMessage = errorMessage || `API Error: ${response.status}`;
        throw new Error(typeof errorMessage === 'string' ? errorMessage : JSON.stringify(errorMessage));
      }

      const data = await response.json();
      
      // Handle OpenAI format
      if (data.choices && data.choices.length > 0 && data.choices[0].message) {
        return data.choices[0].message.content;
      }
      // Handle Ollama native format
      if (data.response) {
        return data.response;
      }
      // Handle Anthropic format
      if (data.content && Array.isArray(data.content)) {
        return data.content[0].text;
      }
      // Handle raw text fallback from our proxy
      if (data.rawResponse) {
        return data.rawResponse;
      }
      
      // If we don't know the format, throw an error with the stringified data so the user can see it
      throw new Error(`Unexpected API response format: ${JSON.stringify(data).substring(0, 200)}...`);
    } catch (error) {
      console.warn(`Failed with model ${model}:`, error);
      lastError = error;
    }
  }

  console.warn('All configured models failed, falling back to default Gemini model.');
  try {
    const response = await defaultAi.models.generateContent({
      model: 'gemini-2.5-flash',
      contents: prompt,
    });
    if (response.text) return response.text;
  } catch (geminiError) {
    console.error('Fallback Gemini also failed:', geminiError);
  }

  throw lastError || new Error('All models failed');
}

function cleanJSON(text: string): string {
  if (!text) return '';
  let cleanText = text.trim();
  
  // Try to extract JSON block if markdown is used
  const jsonMatch = cleanText.match(/```(?:json)?\s*([\s\S]*?)\s*```/);
  if (jsonMatch && jsonMatch[1]) {
    return jsonMatch[1].trim();
  }
  
  // Fallback: try to find the first [ or { and last ] or }
  const firstBrace = cleanText.indexOf('{');
  const lastBrace = cleanText.lastIndexOf('}');
  const firstBracket = cleanText.indexOf('[');
  const lastBracket = cleanText.lastIndexOf(']');
  
  // Determine if it's an array or object based on what comes first
  const hasBracket = firstBracket !== -1 && lastBracket !== -1;
  const hasBrace = firstBrace !== -1 && lastBrace !== -1;

  if (hasBracket && (!hasBrace || firstBracket < firstBrace)) {
    return cleanText.substring(firstBracket, lastBracket + 1);
  } else if (hasBrace) {
    return cleanText.substring(firstBrace, lastBrace + 1);
  }
  
  return cleanText;
}

export async function generateChunk(params: GenerateChunkParams): Promise<GeneratedChunkResponse> {
  const { resources, rTotal, iValue, uTotal, settings, theme, sentenceLength } = params;
  const resourceList = resources.map(r => `${r.name} (${r.color}, ${r.ohm} Ohm)`).join(', ');

const prompt = `
You are an expert linguist and curriculum designer for an EdTech system called "CHUNKS".
Your task is to generate a bilingual sentence (Vietnamese first, then English) based on a set of input resources and a specific algorithm.

Target Theme/Topic: ${theme || 'General Conversation'}
Desired Sentence Length: ${sentenceLength || 'Medium'}

Algorithm Context:
- U = I * R
- R (Resistance): Base difficulty of resources. Total R = ${rTotal}
- I (Current/MSE): Context/complexity variable. I = ${iValue}
- U (Voltage): Total lesson energy/difficulty. U = ${uTotal}

Input Resources to include in the sentence:
${resourceList}

Instructions:
1. Primary Goal (Vietnamese First): Start by coming up with a highly natural, meaningful, and contextually logical Vietnamese sentence (or paragraph) that accurately incorporates the exact meaning of all the input resources. Do NOT just list them. Think deeply to create a coherent scenario.
2. English Translation: Translate that Vietnamese concept into a natural-sounding English equivalent. The English version must carry the same semantic integrity and clear intent.
3. Length Calibration: Strictly follow the length constraints: 
   - "Short": Single concise sentence.
   - "Medium": About 2 connected sentences.
   - "Long": A short paragraph of 3 to 4 sentences.
   You must produce a "${sentenceLength || 'Medium'}" length output.
4. Theme Adherence: The context MUST strictly revolve around the theme: ${theme || 'General'}.
5. Energy Level: The structural complexity and vocabulary choice should reflect the U (Voltage) value: ${uTotal}. Higher U means more sophisticated grammar and nuanced meaning.
6. Classification: Assign a relevant thematic category.
7. Output Format: Return ONLY JSON. Ensure the final output is meaningful and accurately uses the input parameters.

Output MUST be strictly in the following JSON format:
{
  "engSentence": "...",
  "vieSentence": "...",
  "category": "...",
  "evaluation": "Explanation of how the resources create a meaningful context matching the U: ${uTotal}"
}
`;
  const responseText = await callAI(prompt, settings);
  const cleanText = cleanJSON(responseText);
  try {
    return JSON.parse(cleanText) as GeneratedChunkResponse & { evaluation?: string };
  } catch (e) {
    console.error("Failed to parse AI response:", cleanText);
    throw new Error(`AI returned invalid JSON format: ${e instanceof Error ? e.message : 'Unknown error'}`);
  }
}

export async function generateAutoChunks(params: AutoGenerateParams): Promise<AutoGeneratedChunk[]> {
  const { theme, targetU, quantity, sentenceLength, colorPreferences, availableResources, settings } = params;

  // Pre-filter resources to balance them based on color preferences and target U
  const filteredAvailable = availableResources
    .filter(r => colorPreferences.length === 0 || colorPreferences.includes(r.color))
    .sort((a, b) => Math.abs(a.ohm - (targetU / 3)) - Math.abs(b.ohm - (targetU / 3))) // Heuristic: try to find resources that are roughly 1/3 of target U
    .slice(0, 150);

  const resourceList = filteredAvailable.map(r => ({
    id: r.id,
    name: r.name,
    color: r.color,
    ohm: r.ohm
  }));

const prompt = `
You are a Master Linguistic Architect for the "CHUNKS" EdTech system.
Your mission is to construct ${quantity} high-quality learning chunks.

Theme: ${theme}
Target Voltage (U): ${targetU}
Sentence Length: ${sentenceLength} ("Short": 1 sentence, "Medium": 2 sentences, "Long": 3-4 sentences)
Color Preferences: ${colorPreferences.join(', ')}

Available Ingredients (Resources):
${JSON.stringify(resourceList)}

Physics Logic:
- R_total = Sum(R) for same-color series, then Product of those sums for different colors.
- U = I * R_total (I is the complexity multiplier, default 1.0-2.0).

Construction Flow:
1. Resource Selection: Pick 2-4 resources that mathematically approach the Target U.
2. Vietnamese First Draft: Think deeply and construct a logical, highly natural Vietnamese sentence (or paragraph, reflecting the Sentence Length constraint) encompassing the resources.
3. English Translation: Translate that Vietnamese concept into natural English.
4. Evaluation: SELF-CRITIQUE the sentence. Does it make sense? Is the length appropriate? If not, REGENERATE.
5. Final Validation: Ensure all resources used are from the provided list.

Output strictly as JSON array:
[
  {
    "engSentence": "...",
    "vieSentence": "...",
    "category": "...",
    "resourcesUsed": [...],
    "rTotal": 12.5,
    "iValue": 1.2,
    "uTotal": 15.0,
    "difficultyLabel": "...",
    "evaluation": "Passed: Natural and meaningful."
  }
]
`;

  const responseText = await callAI(prompt, settings);
  const cleanText = cleanJSON(responseText);
  try {
    let results = JSON.parse(cleanText);
    
    // If AI returned a single object instead of an array, wrap it
    if (!Array.isArray(results)) {
      if (typeof results === 'object' && results !== null) {
        // Sometimes AI wraps the array in an object like { "chunks": [...] }
        const possibleArray = Object.values(results).find(v => Array.isArray(v));
        if (possibleArray) {
          results = possibleArray;
        } else {
          results = [results];
        }
      } else {
        throw new Error("Parsed JSON is neither an object nor an array.");
      }
    }
    
    // Filter out any that failed internal AI evaluation if the AI was honest
    return (results as (AutoGeneratedChunk & { evaluation?: string })[])
      .filter(r => !r.evaluation || r.evaluation.toLowerCase().includes('pass'));
  } catch (e) {
    console.error("Failed to parse AI response:", cleanText);
    throw new Error(`AI returned invalid JSON format: ${e instanceof Error ? e.message : 'Unknown error'}`);
  }
}
