import { GoogleGenAI } from "@google/genai";
import { Resource, ColorCategory, AISettings, SentenceLength } from "../types";

// Isomorphic origin: works in both browser and Node.js (server-side)
const APP_ORIGIN =
  typeof window !== "undefined"
    ? window.location.origin
    : "https://chunks-cvr.web.app";

// We lazily instantiate the Gemini client to avoid startup crashes if the key is completely missing
function getGeminiClient(customKey?: string) {
  const key = customKey || process.env.GEMINI_API_KEY;
  if (!key) {
    throw new Error(
      "No Gemini API Key available. Please specify an API key in your AI Configuration.",
    );
  }
  return new GoogleGenAI({ apiKey: key });
}

export interface GenerateChunkParams {
  resources: Resource[];
  rTotal: number;
  iValue: number;
  uTotal: number;
  theme?: string;
  topicLevel?: number;
  sentenceLength?: SentenceLength;
  settings?: AISettings;
}

export interface GeneratedChunkResponse {
  engSentence: string;
  vieSentence: string;
  category: string;
}

export interface AutoGenerateParams {
  theme: string;
  topicLevel?: number;
  targetU: number;
  quantity: number;
  sentenceLength: SentenceLength;
  colorPreferences: ColorCategory[];
  availableResources: Resource[];
  settings?: AISettings;
}

export interface AutoGeneratedChunk extends GeneratedChunkResponse {
  resourcesUsed: Resource[];
  rTotal: number;
  iValue: number;
  uTotal: number;
  difficultyLabel: string;
  audioUrl?: string | null;
}

export interface LCBreakdown {
  sentenceCount: number;
  wordCount: number;
  lengthBand: string;
  lcValue: number;
  reasoning: string;
}

export interface TCBreakdown {
  matchedResources: any[];
  candidateResources: any[];
  confirmedTC: number;
  estimatedTC: number;
  calculation: string;
}

export interface TLBreakdown {
  band: string;
  tlValue: number;
  confidence: number;
  reasoning: string;
}

export interface CVRResult {
  transcriptRaw: string;
  transcriptNormalized: string;
  lcBreakdown: LCBreakdown;
  tcBreakdown: TCBreakdown;
  tlBreakdown: TLBreakdown;
  predictedCVR: number;
  formula: string;
  calculationString: string;
}

export async function transcribeAudio(
  audioBlob: Blob,
  settings?: AISettings,
): Promise<string> {
  const base64Audio = await new Promise<string>((resolve, reject) => {
    const reader = new FileReader();
    reader.onloadend = () => {
      const base64 = (reader.result as string).split(",")[1];
      resolve(base64);
    };
    reader.onerror = reject;
    reader.readAsDataURL(audioBlob);
  });

  const apiKey = settings?.geminiApiKey || process.env.GEMINI_API_KEY;
  const aiClient = getGeminiClient(apiKey);
  const modelToUse = settings?.audioTranscriptModel || "gemini-2.5-flash";

  const response = await aiClient.models.generateContent({
    model: modelToUse,
    contents: [
      {
        inlineData: {
          mimeType: audioBlob.type || "audio/webm",
          data: base64Audio,
        },
      },
      "Please transcribe this audio. Return ONLY the transcript text in the language spoken, with no other commentary, quotes, or formatting.",
    ],
  });
  return response.text ? response.text.trim() : "";
}

export async function measureCVR(
  transcript: string,
  settings?: AISettings,
  baseOhms?: Record<string, number>,
  resources?: Resource[],
  tcCorrections?: Array<{sentence_fragment: string, resource_name: string, color: string, ohm: number}>,
): Promise<CVRResult> {
  const rawOhms = settings?.ohmBaseValues ||
    baseOhms || { Green: 5, Blue: 7, Red: 9, Pink: 3 };
  
  // Normalize to uppercase for easier AI matching
  const r = rawOhms as Record<string, number>;
  const ohms: Record<string, number> = {
    GREEN: Number(r.Green || r.GREEN || 5),
    BLUE: Number(r.Blue || r.BLUE || 7),
    RED: Number(r.Red || r.RED || 9),
    PINK: Number(r.Pink || r.PINK || 3),
  };

  // Strip punctuation and extra spaces for robust matching against transcript typos
  const stripPunctuation = (str: string) =>
    str
      .normalize("NFC")
      .toLowerCase()
      .replace(/[\s\u200B-\u200D\uFEFF]+/g, " ")
      .replace(/[.,!?;:"‘’“”\\'(){}\[\]<>—-]/g, "")
      .trim();
  const trStripped = stripPunctuation(transcript);

  type MatchedResource = {
    text: string;
    color: ColorCategory;
    ohm: number;
    matchStart: number;
    matchEnd: number;
    matchText: string;
    matchWordCount: number;
    specificity: number;
  };

  const wordCountOf = (str: string) =>
    str.split(/\s+/).filter((w) => w.trim().length > 0).length;

  const findExactSpan = (phrase: string) => {
    const v = phrase.trim();
    if (!v) return null;
    const paddedTranscript = ` ${trStripped} `;
    const paddedNeedle = ` ${v} `;
    const pos = paddedTranscript.indexOf(paddedNeedle);
    if (pos < 0) return null;
    return { start: pos, end: pos + v.length, matchText: v };
  };

  const findOrderedWildcardSpan = (alt: string) => {
    const rawSegments = alt
      .split(/\.{2,}|…/g)
      .map((part) => stripPunctuation(part.replace(/\//g, " ")).trim())
      .filter((part) => part.length > 0);

    if (rawSegments.length === 0) return null;
    if (rawSegments.length === 1) return findExactSpan(rawSegments[0]);

    let searchFrom = 0;
    let start = -1;
    let end = -1;

    for (const segment of rawSegments) {
      const paddedRemaining = ` ${trStripped.slice(searchFrom)} `;
      const paddedSegment = ` ${segment} `;
      const relativePos = paddedRemaining.indexOf(paddedSegment);
      if (relativePos < 0) return null;

      const segmentStart = searchFrom + relativePos;
      const segmentEnd = segmentStart + segment.length;
      if (start < 0) start = segmentStart;
      end = segmentEnd;
      searchFrom = segmentEnd;
    }

    return {
      start,
      end,
      matchText: trStripped.slice(start, end).trim(),
    };
  };

  const buildInlineSlashVariations = (alt: string) => {
    const cleaned = alt.replace(/\.{2,}|…/g, " ").trim();
    const wordsArr = cleaned.split(/\s+/).filter((w) => w.length > 0);
    let variations: string[][] = [[]];

    for (const word of wordsArr) {
      if (word.includes("/")) {
        const parts = word.split("/");
        const newVars: string[][] = [];
        for (const part of parts) {
          if (part && part.trim() !== "") {
            for (const v of variations) {
              newVars.push([...v, part]);
            }
          }
        }
        if (newVars.length > 0) variations = newVars;
      } else {
        for (const v of variations) v.push(word);
      }
    }

    return variations
      .map((vArr) => stripPunctuation(vArr.join(" ")).trim())
      .filter((v) => v.length > 0);
  };

  const rawMatched: MatchedResource[] = [];

  if (resources && resources.length > 0) {
    resources.forEach((resource) => {
      const alternatives = resource.name.split(/ \/ /);
      let bestMatch: MatchedResource | null = null;

      for (const alt of alternatives) {
        const possibleSpans: Array<{ start: number; end: number; matchText: string; wildcard: boolean }> = [];
        const altCore = stripPunctuation(alt.replace(/\.{2,}|…/g, " ").replace(/\//g, " ")).trim();
        const altWordCount = wordCountOf(altCore);
        const skipShortMultiAlternative = alternatives.length > 1 && altWordCount <= 2;

        const wildcardSpan = skipShortMultiAlternative ? null : findOrderedWildcardSpan(alt);
        if (wildcardSpan) possibleSpans.push({ ...wildcardSpan, wildcard: /\.{2,}|…/.test(alt) });

        const textVariations = buildInlineSlashVariations(alt);
        textVariations.push(stripPunctuation(alt.replace(/\//g, " ")).trim());

        const uniqueVars = Array.from(new Set(textVariations));
        for (const v of uniqueVars) {
          const vWordCount = wordCountOf(v);
          if (v && vWordCount === 1 && resource.name.trim().split(/[\s/]+/).length >= 3) continue;
          if (v && vWordCount <= 2 && alternatives.length > 1) continue;

          const exactSpan = findExactSpan(v);
          if (exactSpan) possibleSpans.push({ ...exactSpan, wildcard: false });
        }

        for (const span of possibleSpans) {
          const matchWordCount = wordCountOf(span.matchText);
          const specificity = matchWordCount + (span.wildcard ? 1.5 : 0) + Math.min(resource.ohm, 10) / 100;
          const candidate: MatchedResource = {
            text: resource.name,
            color: resource.color,
            ohm: Number(resource.ohm),
            matchStart: span.start,
            matchEnd: span.end,
            matchText: span.matchText,
            matchWordCount,
            specificity,
          };

          if (!bestMatch || candidate.specificity > bestMatch.specificity) {
            bestMatch = candidate;
          }
        }
      }

      if (bestMatch) rawMatched.push(bestMatch);
    });
  }

  const dedupeOverlappingResources = (items: MatchedResource[]) => {
    const sorted = [...items].sort((a, b) => {
      const aSpan = a.matchEnd - a.matchStart;
      const bSpan = b.matchEnd - b.matchStart;
      return b.specificity - a.specificity || bSpan - aSpan || b.ohm - a.ohm || b.text.length - a.text.length;
    });

    const selected: MatchedResource[] = [];
    for (const item of sorted) {
      const isDuplicate = selected.some((chosen) => {
        const overlap = Math.max(0, Math.min(item.matchEnd, chosen.matchEnd) - Math.max(item.matchStart, chosen.matchStart));
        if (overlap <= 0) return false;
        const itemSpan = Math.max(1, item.matchEnd - item.matchStart);
        const chosenSpan = Math.max(1, chosen.matchEnd - chosen.matchStart);
        const smallerCoverage = overlap / Math.min(itemSpan, chosenSpan);
        const eitherContainsText =
          item.matchText.includes(chosen.matchText) || chosen.matchText.includes(item.matchText);
        return smallerCoverage >= 0.6 || eitherContainsText;
      });

      if (!isDuplicate) selected.push(item);
    }

    return selected.sort((a, b) => a.matchStart - b.matchStart);
  };

  // Matched TC is deterministic and deduped by transcript span.
  // This prevents double-counting aliases/subphrases such as "Nãy giờ" inside
  // "Thì tui đã nói nãy giờ...", and prefers longer wildcard resources such as
  // "Uả, cậu là... hay gì?!?" over short aliases like "Uả!...".
  const matched = dedupeOverlappingResources(rawMatched);

  const confirmedTC = matched.reduce((acc, curr) => acc + curr.ohm, 0);

  const matchedStr =
    matched.length > 0
      ? `\n\nCác resources đã match sẵn trong thư viện (Confirmed TC = ${confirmedTC}):\n` +
        matched.map((m) => `- "${m.text}" (${m.color} ${m.ohm}Ω)`).join("\n")
      : `\n\nKhông có resources nào trong thư viện match với đoạn Transcript. (Confirmed TC = 0)`;

  const correctionsStr =
    tcCorrections && tcCorrections.length > 0
      ? `\n\n## Lịch sử Corrections đã xác nhận (ưu tiên tham khảo khi gặp cụm từ tương tự):\n` +
        tcCorrections.slice(0, 20).map((c) => `- "${c.sentence_fragment}" → ${c.color} ${c.ohm}Ω`).join("\n")
      : "";

  const multipliers = settings?.complexityMultipliers || {
    "Very Short": 1,
    Short: 1.5,
    Medium: 2,
    Long: 2.5,
  };
  const constraints = settings?.sentenceConstraints || {
    "Very Short": { maxSentences: 1, maxWords: 18 },
    Short: { maxSentences: 2, maxWords: 30 },
    Medium: { maxSentences: 3, maxWords: 60 },
    Long: { maxSentences: 5, maxWords: 100 },
  };

  // 1. Calculate LC Deterministically (Strict Words Buckets)
  const sentences =
    transcript.split(/[.?!]+/).filter((s) => s.trim().length > 0).length || 1;
  const words =
    transcript.split(/\s+/).filter((w) => w.trim().length > 0).length || 0;

  let selectedBand: SentenceLength = "Long";

  const vsMaxWords = Number(constraints["Very Short"]?.maxWords) || 18;
  const sMaxWords = Number(constraints["Short"]?.maxWords) || 30;
  const mMaxWords = Number(constraints["Medium"]?.maxWords) || 60;
  const lMaxWords = Number(constraints["Long"]?.maxWords) || 100;

  // We are evaluating based strictly on word counts as requested
  if (words <= vsMaxWords) {
    selectedBand = "Very Short";
  } else if (words <= sMaxWords) {
    selectedBand = "Short";
  } else if (words <= mMaxWords) {
    selectedBand = "Medium";
  } else {
    selectedBand = "Long";
  }

  const lcValue = multipliers[selectedBand] || 1;

  const reasoningString = `Determined by engine constraints (Words mode). The transcript has ${words} words. The configured bounds are: Very Short (≤${vsMaxWords}), Short (≤${sMaxWords}), Medium (≤${mMaxWords}), Long (>${mMaxWords}). Because ${words} falls into the ${selectedBand} bucket, it was classified as ${selectedBand} (Multiplier: ${lcValue}).`;

  const defaultInstructions = `
Bạn là CVR Measure Engine. Nhiệm vụ của bạn là phân tích đoạn Transcript tiếng Việt để tìm ra độ khó (CVR) dựa trên 3 yếu tố:

1. TC (Total Resource Ohm load): Bóc tách các cụm từ (trừ các từ ngữ đã match ở trên) làm Resource Candidates.
   --- STRICT VOCABULARY MAPPING RULES ---
   - PINK (${ohms.PINK}Ω): Key Concepts / Technical Terms. 
     *CHỈ ĐỊNH:* Chỉ dành cho danh từ hoặc thuật ngữ có độ khó từ B1 trở lên (CEFR). Phải là các từ mang tính kỹ thuật, định danh chuyên biệt hoặc từ vựng không phổ biến. 
     *LOẠI TRỪ:* Các từ vựng căn bản (A1-A2) như "nhà", "xe", "điện thoại", "ăn cơm" KHÔNG được tính là PINK dù chúng là danh từ chính. 
     Ví dụ: "Ví điện tử", "Thị thực", "Lạm phát", "Dép lào".
   - GREEN (${ohms.GREEN}Ω): Từ đệm, từ nối hoặc từ điều hướng (Discourse Markers / Fillers / Conditioners). Dùng để định hướng câu nói, tạo sự tự nhiên hoặc làm mềm ngữ cảnh. Ví dụ: Tin tui đi, Thành thật mà nói, Nói chung là.
   - BLUE (${ohms.BLUE}Ω): Khung câu hoặc cấu trúc ngữ pháp (Sentence Frames / Grammatical Skeletons). Các cấu trúc chờ được lấp đầy nội dung. Ví dụ: Cậu nên nhớ rằng..., Tui không ngờ là..., Vấn đề không phải là....
   - RED (${ohms.RED}Ω): Idioms / Metaphors / Nuanced Expressions. 
     *CHỈ ĐỊNH:* Các cụm từ không mang nghĩa đen, đòi hỏi sự hiểu biết về văn hóa hoặc tư duy hình ảnh. 
     *BẢN CHẤT:* Độ phức tạp nằm ở tầng ngữ nghĩa (semantics) và sự bóng bẩy, không phải độ khó của từ vựng đơn lẻ. 
     Ví dụ: "Mật ngọt chết ruồi", "Cậu tới số rồi", "Vắt chân lên cổ", "Cái nết đánh chết cái đẹp".
   *QUAN TRỌNG: Phân loại theo chức năng ngôn ngữ của cụm từ trong câu, không phải theo độ phổ biến của từ đơn lẻ.*

   - Tính Confirmed TC = Tổng Ohm của các resources đã match.
   - Tính Estimated TC = Confirmed TC + Tổng Ohm của các Resource Candidates.
2. LC (Length-Complexity): Đã được tính toán bằng Engine: ${sentences} câu, ${words} từ => Band: ${selectedBand}, Multiplier: ${lcValue}. Không cần tính lại.
3. TL (Topic/Vocabulary Level): Đánh giá theo HAI TRỤC ĐỘC LẬP, lấy max().

   --- TRỤC T: Topic/Discourse Level ---
   T=1.0: Sinh hoạt đời thường, không có chuyên môn (mua sắm, thời tiết, gia đình, chuyện trò hàng ngày)
          Ví dụ: "Hôm nay trời đẹp, tôi đi chợ mua rau."
   T=1.3: Xã hội, tâm lý phức tạp, nghề nghiệp phổ thông (bán hàng, giáo viên phổ thông, y tá, văn phòng)
          Ví dụ: "Áp lực công việc khiến nhiều nhân viên kiệt sức và khó giữ cân bằng cuộc sống."
   T=1.6: Chuyên môn thực hành rõ ràng — giao tiếp nghề nghiệp chuẩn (y bác sĩ, luật sư, kỹ sư, chuyên viên tài chính cấp cơ bản đến trung)
          Ví dụ: "Bác sĩ chẩn đoán bệnh nhân mắc hội chứng chuyển hóa và đề nghị điều chỉnh lối sống."
   T=1.8: Phân tích học thuật / chính sách / nghiên cứu liên ngành (kinh tế học, y tế công cộng, chính sách pháp luật, quản trị tổ chức phức tạp, nghiên cứu xã hội học)
          Ví dụ: "Các cơ chế tài chính vi mô chưa đủ mạnh để giải quyết bất đối xứng thông tin trong thị trường tín dụng nông thôn."
   T=2.0: Nghiên cứu chuyên ngành hẹp / học thuật đỉnh cao (triết học meta-lý thuyết, vật lý lý thuyết, kinh tế học toán, lâm sàng nghiên cứu chuyên sâu)
          Ví dụ: "Tính không đầy đủ thị trường Arrow-Debreu trong điều kiện rủi ro đạo đức nội sinh đòi hỏi cơ chế ưu đãi phi tuyến."

   --- TRỤC V: Vocabulary/Lexical Difficulty ---
   V=1.0: A1-A2 — từ tần suất rất cao, ai cũng biết (nhà, xe, ăn, đi, mua, đẹp, vui)
   V=1.2: B1 — từ trung cấp phổ thông (quyết định, hài lòng, thủ tục, cơ hội, ảnh hưởng)
   V=1.4: B2 — từ trung-cao, cần học chủ động (tiêu thụ, phân tích, dự báo, bất bình đẳng, hiệu quả)
   V=1.6: C1 — từ học thuật/chuyên môn phổ biến trong giới chuyên nghiệp (cơ chế, bất đối xứng, minh bạch, phân bổ nguồn lực, tích lũy, đồng thuận)
   V=1.8: C2 — từ/cụm từ học thuật chuyên ngành, ít xuất hiện ngoài văn bản chuyên môn (bất đối xứng thông tin, tài chính vi mô, hệ số co giãn, phân tích đa biến, trung gian hóa)
   V=2.0: Thuật ngữ siêu chuyên biệt, chỉ dùng trong tài liệu nghiên cứu hẹp (hàm Lagrangian, giảo luận siêu hình, đồng phân lập thể, meta-phân tích RCT)

   --- QUY TẮC KẾT HỢP ---
   TL = max(T, V)   →  làm tròn 0.1 gần nhất, clamp [1.0, 2.0]
   *Ví dụ: Chủ đề đời sống (T=1.0) nhưng dùng từ C1 (V=1.6) → TL=1.6*
   *Ví dụ: Chủ đề y khoa thực hành (T=1.6) nhưng dùng từ A2 (V=1.0) → TL=1.6*
   *Ví dụ: Phân tích chính sách tài chính nông thôn (T=1.8) + từ C2 (V=1.8) → TL=1.8*
   *Ví dụ: Nghiên cứu kinh tế học toán (T=2.0) + thuật ngữ hẹp (V=2.0) → TL=2.0*

   ⚠️ ANTI-BIAS RULE: Đừng mặc định dừng ở 1.6 khi transcript rõ ràng là academic/policy/nghiên cứu liên ngành.
   Nếu topic là phân tích chính sách, nghiên cứu học thuật, hoặc ngôn ngữ chuyên ngành phức tạp → T ≥ 1.8.
   Nếu vocab ngoài TC resources gồm nhiều từ C2 hoặc thuật ngữ chuyên ngành hẹp → V ≥ 1.8.
   TL=1.6 chỉ đúng cho giao tiếp nghề nghiệp THỰC HÀNH (bác sĩ nói chuyện với bệnh nhân, luật sư tư vấn thông thường). TL=1.8+ dành cho phân tích/nghiên cứu/viết học thuật.

   IMPORTANT: Idioms/metaphors (RED) và Technical Terms (PINK) đã được tính vào TC. Khi đánh giá Trục V, hãy nhìn vào từ vựng NGOÀI các TC resources — các tính từ, động từ, danh từ chức năng trong câu.

Công thức cuối: CVR = Estimated TC * LC * TL.
`;

  const systemInstructions = defaultInstructions;

  const prompt = `
${systemInstructions}

Transcript:
"${transcript}"
${matchedStr}${correctionsStr}

Return the result STRICTLY as a JSON object with this structure:
{
  "transcriptRaw": "...",
  "transcriptNormalized": "...",
  "lcBreakdown": {
    "sentenceCount": ${sentences},
    "wordCount": ${words},
    "lengthBand": "${selectedBand}",
    "lcValue": ${lcValue},
    "reasoning": "Determined by Engine constraints."
  },
  "tcBreakdown": {
    "matchedResources": [ ${matched.length > 0 ? `{"text": "${matched[0].text}", "color": "${matched[0].color}", "ohm": ${matched[0].ohm}}` : ""} ],
    "candidateResources": [
      {
         "text": "cụm từ 1",
         "color": "RED",
         "ohm": ${ohms.RED},
         "confidence": 0.9,
         "reasoning": "..."
      }
    ],
    "confirmedTC": ${confirmedTC},
    "estimatedTC": ${confirmedTC},
    "calculation": "${confirmedTC} (Confirmed) + ..."
  },
  "tlBreakdown": {
    "band": "A1-A2",
    "tlValue": 1.0,
    "confidence": 0.9,
    "reasoning": "..."
  },
  "predictedCVR": ${confirmedTC * lcValue * 1.0},
  "formula": "Estimated TC * LC * TL",
  "calculationString": "..."
}
`;

  const calibrateTopicLevel = (
    aiTlValue: number,
    aiReasoning: string,
    tcOverflow: Array<{ text?: string; name?: string; color: string; ohm: number; type: string }> = [],
  ): TLBreakdown => {
    // Normalization and boundary enforcement
    const finalTl = Math.max(1.0, Math.min(2.0, Number(aiTlValue) || 1.0));

    let band = "TL 1.0-1.2 Daily life / casual routine";
    if (finalTl >= 1.8) {
      band = "TL 1.8-2.0 Specialized professional/academic";
    } else if (finalTl >= 1.3) {
      band = "TL 1.3-1.7 Social/Professional/Nuanced domain";
    }

    let overflowNote = "";
    if (tcOverflow.length > 0) {
      const overflowStr = tcOverflow
        .map((r) => `"${r.text || r.name}" (${r.color} ${r.ohm}Ω, ${r.type})`)
        .join(", ");
      overflowNote = ` | TC-Derived TL Evidence (overflow — counted in TL context, not TC): ${overflowStr}`;
    }

    return {
      band,
      tlValue: finalTl,
      confidence: 0.9,
      reasoning: `AI-Driven Analysis: ${aiReasoning}${overflowNote}`,
    };
  };

  const responseText = await callAI(prompt, settings);
  try {
    const jsonMatch =
      responseText.match(/```json\n([\s\S]*?)\n```/) ||
      responseText.match(/\{[\s\S]*\}/);
    const jsonString = jsonMatch ? jsonMatch[1] || jsonMatch[0] : responseText;
    const result = JSON.parse(jsonString) as CVRResult;

    // Force Deterministic LC overwrite to prevent hallucinations
    result.lcBreakdown = {
      sentenceCount: sentences,
      wordCount: words,
      lengthBand: selectedBand,
      lcValue: lcValue,
      reasoning: reasoningString,
    };

    // Normalize, enforce candidate Ohms, and remove candidates that overlap confirmed resources.
    const rawCandidates = result.tcBreakdown.candidateResources || [];
    const forcedCandidatesRaw = rawCandidates.map((c: any) => {
      const color = (c.color || "").toUpperCase();
      const enforcedOhm = ohms[color] || 0;
      return {
        ...c,
        text: String(c.text || "").trim(),
        color: color.charAt(0) + color.slice(1).toLowerCase(), // Normalize back to 'Red', 'Green', etc.
        ohm: enforcedOhm,
        type: "candidate",
        normalizedText: stripPunctuation(String(c.text || "")).trim(),
      };
    });

    const forcedCandidates = forcedCandidatesRaw.filter((candidate, idx, arr) => {
      const candidateText = candidate.normalizedText;
      if (!candidateText || candidate.ohm <= 0) return false;

      const overlapsMatched = matched.some((m) => {
        const matchText = stripPunctuation(m.matchText || m.text).trim();
        return (
          matchText.includes(candidateText) ||
          candidateText.includes(matchText)
        );
      });
      if (overlapsMatched) return false;

      const duplicateIdx = arr.findIndex((other) => {
        const otherText = other.normalizedText;
        return (
          otherText === candidateText ||
          (otherText && candidateText && (otherText.includes(candidateText) || candidateText.includes(otherText)))
        );
      });

      return duplicateIdx === idx;
    });

    // Force Deterministic TC accumulation with capping!
    result.tcBreakdown.matchedResources = matched;

    const defaultSlotsPerBand: Record<SentenceLength, number> = {
      "Very Short": 2,
      Short: 3,
      Medium: 4,
      Long: 5,
    };
    const slotsPerBand = settings?.tcSlotsPerBand || defaultSlotsPerBand;
    const maxAllowedResources = slotsPerBand[selectedBand] ?? defaultSlotsPerBand[selectedBand];

    // Fill strategy: matched always come first (highest ohm within matched).
    // For candidates, sort by configured strategy: 'highest-ohm' (default) or 'lowest-ohm'.
    const fillStrategy = settings?.tcCandidateFillStrategy || "highest-ohm";

    const allResources = [
      ...matched.map((m) => ({ ...m, type: "matched" })),
      ...forcedCandidates,
    ];

    allResources.sort((a, b) => {
      if (a.type === "matched" && b.type !== "matched") return -1;
      if (a.type !== "matched" && b.type === "matched") return 1;
      if (a.type === "candidate" && b.type === "candidate") {
        return fillStrategy === "lowest-ohm" ? a.ohm - b.ohm : b.ohm - a.ohm;
      }
      // Both matched: always highest ohm first
      return b.ohm - a.ohm;
    });

    const includedResources = allResources.slice(0, maxAllowedResources);
    const overflowResources = allResources.slice(maxAllowedResources);

    const includedTC = includedResources.reduce((acc, curr) => acc + curr.ohm, 0);

    // confirmedTC = only matched resources that fit within the slot cap (not all matched).
    // This keeps confirmedTC <= estimatedTC per CONTEXT.md invariant.
    const includedMatched = includedResources.filter((r) => r.type === "matched");
    result.tcBreakdown.confirmedTC = includedMatched.reduce((acc, curr) => acc + curr.ohm, 0);
    result.tcBreakdown.candidateResources = forcedCandidates;
    result.tcBreakdown.estimatedTC = includedTC;

    let calcStr = includedResources
      .map((r) => `${r.ohm} (${r.type})`)
      .join(" + ");
    if (overflowResources.length > 0) {
      calcStr += ` ... [+${overflowResources.length} overflow item(s) → TL evidence]`;
    }
    if (includedResources.length === 0) calcStr = "0";

    result.tcBreakdown.calculation = `${calcStr} = ${includedTC} (Capped at ${maxAllowedResources} slots for ${selectedBand}, fill: ${fillStrategy})`;

    // Recalculate exactly CVR with deterministic TL calibrated to The Mixer's topic-level definitions.
    // Overflow resources are not counted in estimatedTC but are passed as TC-Derived TL Evidence.
    result.tlBreakdown = calibrateTopicLevel(
      Number(result.tlBreakdown?.tlValue) || 1.0,
      result.tlBreakdown?.reasoning || "No reasoning provided by AI.",
      overflowResources,
    );
    const finalCVR =
      result.tcBreakdown.estimatedTC *
      result.lcBreakdown.lcValue *
      result.tlBreakdown.tlValue;
    result.predictedCVR = Math.max(1, Math.round(finalCVR));
    result.calculationString = `${result.tcBreakdown.estimatedTC} (TC) × ${result.lcBreakdown.lcValue} (LC) × ${result.tlBreakdown.tlValue} (TL) = ${result.predictedCVR}`;

    return result;
  } catch (error) {
    console.error("Failed to parse analysis result:", responseText);
    throw new Error("Failed to parse analysis result from AI.");
  }
}

export async function fetchOpenRouterModels(
  apiKey: string,
  endpoint: string = "https://openrouter.ai/api/v1",
) {
  if (!apiKey) return [];
  try {
    const response = await fetch(
      `${endpoint.replace(/\/+$/, "")}/models`,
      {
        method: "GET",
        headers: {
          Authorization: `Bearer ${apiKey}`,
          "HTTP-Referer": APP_ORIGIN,
          "X-Title": "CHUNKS CVR",
        },
      },
    );
    if (!response.ok)
      throw new Error(`Failed to fetch models: ${response.statusText}`);
    const data = await response.json();
    return data.data || [];
  } catch (error) {
    console.error("Error fetching models:", error);
    throw error;
  }
}

async function callAI(prompt: string, settings?: AISettings): Promise<string> {
  const apiKey = settings?.apiKey;
  const primaryModel = settings?.primaryModel || "gemini-2.0-flash";
  const fallbackModel = settings?.fallbackModel || "gemini-1.5-flash";

  // If no custom API key is provided, we use the default Gemini client with the configured model
  if (!apiKey) {
    try {
      const gClient = getGeminiClient();
      const response = await gClient.models.generateContent({
        model: primaryModel,
        contents: prompt,
        config: {
          responseMimeType: "application/json",
        },
      });
      if (response.text) return response.text;
    } catch (error) {
      console.warn(
        `Default model ${primaryModel} failed, trying fallback ${fallbackModel}:`,
        error,
      );
      const gClient = getGeminiClient();
      const response = await gClient.models.generateContent({
        model: fallbackModel,
        contents: prompt,
        config: {
          responseMimeType: "application/json",
        },
      });
      if (!response.text) throw new Error("No response from Gemini fallback");
      return response.text;
    }
    throw new Error("Failed to get response from Gemini");
  }

  const { endpoint } = settings;
  const modelsToTry = [primaryModel, fallbackModel].filter(Boolean);
  let lastError = null;

  // ⚠️ Detect Mixed Content early: HTTP endpoint on HTTPS page will always be blocked by browser
  const rawEndpoint = (endpoint || "https://openrouter.ai/api/v1").trim();
  const isHttpsContext = typeof window !== "undefined" && window.location.protocol === "https:";
  if (isHttpsContext && rawEndpoint.startsWith("http:")) {
    throw new Error(
      `Mixed Content Error: Trang web chạy HTTPS nhưng endpoint đang dùng HTTP (${rawEndpoint}). Browser sẽ block request này.\n\n` +
      `Giải pháp:\n` +
      `1. Dùng endpoint HTTPS (nếu server hỗ trợ SSL)\n` +
      `2. Hoặc cấu hình reverse proxy HTTPS → HTTP trên server\n` +
      `3. Hoặc dùng OpenRouter (https://openrouter.ai/api/v1) với API key`
    );
  }

  for (const model of modelsToTry) {
    try {
      const targetEndpoint = rawEndpoint;
      const chatEndpoint = `${targetEndpoint.replace(/\/+$/, "")}/chat/completions`;

      const response = await fetch(chatEndpoint, {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
          Authorization: `Bearer ${apiKey}`,
          "HTTP-Referer": APP_ORIGIN,
          "X-Title": "CHUNKS CVR",
        },
        body: JSON.stringify({
          model: model,
          messages: [{ role: "user", content: prompt }],
          stream: false,
        }),
      });

      if (!response.ok) {
        const errorData = await response.json().catch(() => ({}));
        let errorMessage =
          errorData.error?.message || errorData.error || errorData.message;

        if (!errorMessage && errorData.rawResponse) {
          // Extract text from HTML if it's a Cloudflare error page
          const raw = errorData.rawResponse;
          if (raw.includes("<html") && raw.includes("530")) {
            errorMessage =
              "API Error 530: Cloudflare DNS/Origin error. The AI endpoint might be down or misconfigured.";
          } else {
            errorMessage = `API Error ${response.status}: ${raw.substring(0, 100)}...`;
          }
        }

        errorMessage = errorMessage || `API Error: ${response.status}`;
        throw new Error(
          typeof errorMessage === "string"
            ? errorMessage
            : JSON.stringify(errorMessage),
        );
      }

      const data = await response.json();

      // Handle OpenAI format
      if (data.choices && data.choices.length > 0 && data.choices[0].message) {
        return data.choices[0].message.content;
      }
      // Handle Ollama native format
      if (data.response) {
        return data.response;
      }
      // Handle Anthropic format
      if (data.content && Array.isArray(data.content)) {
        return data.content[0].text;
      }
      // Handle raw text fallback from our proxy
      if (data.rawResponse) {
        // Check if it looks like Server-Sent Events (SSE)
        if (
          typeof data.rawResponse === "string" &&
          data.rawResponse.includes("data: {") &&
          data.rawResponse.includes('"choices"')
        ) {
          let fullContent = "";
          const lines = data.rawResponse.split("\n");
          for (const line of lines) {
            if (line.startsWith("data: ") && line !== "data: [DONE]") {
              try {
                const chunk = JSON.parse(line.substring(6));
                if (
                  chunk.choices &&
                  chunk.choices[0] &&
                  chunk.choices[0].delta &&
                  chunk.choices[0].delta.content
                ) {
                  fullContent += chunk.choices[0].delta.content;
                }
              } catch (e) {
                // Ignore parse errors for individual lines
              }
            }
          }
          if (fullContent) return fullContent;
        }
        return data.rawResponse;
      }

      // If we don't know the format, throw an error with the stringified data so the user can see it
      throw new Error(
        `Unexpected API response format: ${JSON.stringify(data).substring(0, 200)}...`,
      );
    } catch (error) {
      console.warn(`Failed with model ${model}:`, error);
      lastError = error;
    }
  }

  // All custom models failed — throw the real error so the user can see what went wrong.
  // We intentionally do NOT silently fall back to Gemini here, because:
  //  - The user has configured a custom endpoint/model; Gemini is not expected.
  //  - Silently falling back to Gemini with no key produces a confusing "No Gemini API Key" error
  //    that obscures the real problem (wrong endpoint, Mixed Content, bad model name, etc.).
  const errorMsg = lastError instanceof Error ? lastError.message : String(lastError);
  throw new Error(
    `Tất cả models đã thất bại.\n\n` +
    `• Primary model: "${primaryModel}"\n` +
    `• Fallback model: "${fallbackModel}"\n` +
    `• Endpoint: "${rawEndpoint}"\n\n` +
    `Lỗi cuối: ${errorMsg}\n\n` +
    `Kiểm tra lại:\n` +
    `1. Model name đúng format (vd: openai/gpt-4o, anthropic/claude-3-haiku)\n` +
    `2. Endpoint phải HTTPS nếu site chạy HTTPS\n` +
    `3. API Key còn hạn và đúng quyền`
  );
}

function cleanJSON(text: string): string {
  if (!text) return "";
  let cleanText = text.trim();

  // Try to extract JSON block if markdown is used
  const jsonMatch = cleanText.match(/```(?:json)?\s*([\s\S]*?)\s*```/);
  if (jsonMatch && jsonMatch[1]) {
    return jsonMatch[1].trim();
  }

  // Fallback: try to find the first [ or { and last ] or }
  const firstBrace = cleanText.indexOf("{");
  const lastBrace = cleanText.lastIndexOf("}");
  const firstBracket = cleanText.indexOf("[");
  const lastBracket = cleanText.lastIndexOf("]");

  // Determine if it's an array or object based on what comes first
  const hasBracket = firstBracket !== -1 && lastBracket !== -1;
  const hasBrace = firstBrace !== -1 && lastBrace !== -1;

  if (hasBracket && (!hasBrace || firstBracket < firstBrace)) {
    return cleanText.substring(firstBracket, lastBracket + 1);
  } else if (hasBrace) {
    return cleanText.substring(firstBrace, lastBrace + 1);
  }

  return cleanText;
}

export async function generateChunk(
  params: GenerateChunkParams,
): Promise<GeneratedChunkResponse> {
  const {
    resources,
    rTotal,
    iValue,
    uTotal,
    settings,
    theme,
    topicLevel,
    sentenceLength,
  } = params;
  const resourceList = resources
    .map(
      (r) =>
        `${r.name} (${r.color}, ${r.ohm} Ohm${r.hint ? `, Context Hint: ${r.hint}` : ""})`,
    )
    .join(", ");

  const currentLen = sentenceLength || "Medium";
  const constraints = settings?.sentenceConstraints?.[currentLen];

  const targetSentences =
    constraints?.maxSentences ||
    (currentLen === "Very Short"
      ? 1
      : currentLen === "Short"
        ? 2
        : currentLen === "Medium"
          ? 3
          : 5);
  const targetWords =
    constraints?.maxWords ||
    (currentLen === "Very Short"
      ? 15
      : currentLen === "Short"
        ? 30
        : currentLen === "Medium"
          ? 60
          : 100);
  const minWords = Math.max(5, Math.floor(targetWords * 0.8));

  const prompt = `
You are an expert linguist and curriculum designer for an EdTech system called "CHUNKS".
Your task is to generate a bilingual sentence (Vietnamese first, then English) based on a set of input resources and a specific algorithm.

Target Theme/Topic: ${theme === "INFER_FROM_RESOURCES" ? "Dynamically infer the most logical and specific theme entirely based on the provided Input Resources. Do NOT use a random theme." : theme ? theme : "Dynamically formulate a random specific theme that completely aligns with the STRICT TL MAPPING RULES below. Do not be generic."}
Topic Level (TL target): ${topicLevel || 1.0}
--- STRICT TL MAPPING RULES ---
- TL 1.0 - 1.2: Daily life, casual chat, standard routines. (A1-A2 vocabulary)
- TL 1.3 - 1.7: Social issues, professional work, academic study, intermediate lifestyle. (B1-B2 vocabulary)
- TL 1.8 - 2.0: Industry-specific discussions, complex operations, business strategies, intellectual discussions, specialized academia. (B2-C1 vocabulary, highly advanced professional/academic communication)
***ABSOLUTE RULE FOR HIGH TL (>= 1.8):***
1. You are FORBIDDEN from generating casual, daily-life, or basic interpersonal scenarios.
2. The language MUST be formal, academic, or professional.
3. You MUST use sophisticated English vocabulary (B2/C1 level) appropriate for the topic, but it MUST sound natural in real-world professional or intellectual communication. DO NOT use obscure, archaic, or bizarrely low-frequency C2 words that nobody actually uses.
-------------------------------
Desired Sentence Length: ${currentLen}

Algorithm Context:
- U = I * R
- R (Resistance): Base difficulty of resources. Total R = ${rTotal}
- I (Current/MSE): Context/complexity variable. I = ${iValue}
- U (Voltage): Total lesson energy/difficulty. U = ${uTotal}

Input Resources to include in the sentence:
${resourceList}

*** CRITICAL RULES FOR HINTS ***
1. The 'Context Hint' (if provided) is STRICTLY for the English translation ('engSentence').
2. Do NOT insert the English 'Context Hint' directly into the Vietnamese sentence. The Vietnamese sentence MUST ONLY use the natural Vietnamese word.
3. For example, if the Resource is 'Chị Hằng' and the Hint is 'The Moon Lady':
   - Correct vieSentence: "Giảng viên phân tích hình tượng Chị Hằng."
   - Correct engSentence: "The lecturer analyzed the image of The Moon Lady."
   - INCORRECT vieSentence: "Giảng viên phân tích hình tượng The Moon Lady." (DO NOT do this!)

Instructions:
1. ABSOLUTE PRIORITY (Meaning & Logic): The final result MUST be a highly natural, logical, and meaningful sentence/paragraph in real-life context. Do NOT force words together if they create a nonsensical "Frankenstein" sentence. It MUST sound like something a native speaker would actually say in real conversation.
2. Vietnamese First: Start by constructing a logical Vietnamese scenario encompassing the exact meaning of all input resources. Frame the sentence completely in natural Vietnamese. Do NOT insert any English words from the hints into the Vietnamese sentence.
3. English Translation: Translate that Vietnamese concept into a natural-sounding English equivalent. This is where you apply the 'Context Hint' to translate specific terminology. The English version must carry the same semantic integrity and clear intent.
4. Length Calibration: Strictly follow the length constraints for "${currentLen}"! Calculate the word count based on the VIETNAMESE sentence.
   - You MUST generate EXACTLY ${targetSentences} sentence(s) (if "Very Short", exactly 1 small sentence).
   - The total Vietnamese word count MUST be STRICTLY between ${minWords} and ${targetWords} words. Your sentence should ideally be close to ${targetWords} words, but absolutely NOT less than ${minWords}.
5. Theme Adherence: The context MUST strictly revolve around the requested theme. If no theme is provided, dynamically formulate a specific, highly relevant theme that matches the STRICT TL MAPPING RULES. A casual context for a high TL is a critical failure.
6. Energy Level: The structural complexity and vocabulary choice should reflect the U (Voltage) value: ${uTotal}. Higher U means more sophisticated grammar and nuanced meaning.
7. Classification: Assign a specific thematic category. Ensure the category explicitly reflects the TL tier (e.g. "Supply Chain Management" for TL 1.7, not "General Conversation"). It MUST be extremely concise (Maximum 3-5 words), do NOT generate long descriptive phrases.
8. Output Format: Return ONLY JSON. Ensure the final output is meaningful and accurately uses the input parameters.

Output MUST be strictly in the following JSON format:
{
  "engSentence": "...",
  "vieSentence": "...",
  "category": "...",
  "evaluation": "Explanation of how the resources create a meaningful context matching the U: ${uTotal}"
}
`;
  const responseText = await callAI(prompt, settings);
  if (!responseText || !responseText.trim()) {
    throw new Error(
      "AI returned an empty response. This may be due to safety filters blocking the content or an API error.",
    );
  }
  const cleanText = cleanJSON(responseText);

  try {
    return JSON.parse(cleanText) as GeneratedChunkResponse & {
      evaluation?: string;
    };
  } catch (e) {
    console.error("Failed to parse AI response:", cleanText);
    throw new Error(
      `AI returned invalid JSON format: ${e instanceof Error ? e.message : "Unknown error"}. Response was: ${cleanText.substring(0, 100)}...`,
    );
  }
}

export async function generateAutoChunks(
  params: AutoGenerateParams,
): Promise<AutoGeneratedChunk[]> {
  const {
    theme,
    topicLevel,
    targetU,
    quantity,
    sentenceLength,
    colorPreferences,
    availableResources,
    settings,
  } = params;

  const currentLen = sentenceLength || "Medium";
  const constraints = settings?.sentenceConstraints?.[currentLen];
  const targetSentences =
    constraints?.maxSentences ||
    (currentLen === "Very Short"
      ? 1
      : currentLen === "Short"
        ? 2
        : currentLen === "Medium"
          ? 3
          : 5);
  const targetWords =
    constraints?.maxWords ||
    (currentLen === "Very Short"
      ? 15
      : currentLen === "Short"
        ? 30
        : currentLen === "Medium"
          ? 60
          : 100);
  const minWords = Math.max(5, Math.floor(targetWords * 0.8));

  // Pre-filter resources to balance them based on color preferences and target U
  const filteredAvailable = availableResources
    .filter(
      (r) =>
        colorPreferences.length === 0 || colorPreferences.includes(r.color),
    )
    .sort(
      (a, b) => Math.abs(a.ohm - targetU / 3) - Math.abs(b.ohm - targetU / 3),
    ) // Heuristic: try to find resources that are roughly 1/3 of target U
    .slice(0, 150);

  const resourceList = filteredAvailable.map((r) => ({
    id: r.id,
    name: r.name,
    color: r.color,
    ohm: r.ohm,
    hint: r.hint,
  }));

  const physicsLogic =
    `- R_total = Sum of all individual resource Ohms (R1 + R2 + R3 + ...). Color does not change the math. Example: Pink + Pink + Green = PinkOhm + PinkOhm + GreenOhm.`;

  const prompt = `
You are a Master Linguistic Architect for the "CHUNKS" EdTech system.
Your mission is to construct ${quantity} high-quality learning chunks.

Theme: ${theme ? theme : "Determine dynamically based on Topic Level (TL)"}
Topic Level (TL target): ${topicLevel || 1.0}
--- STRICT TL MAPPING RULES ---
- TL 1.0 - 1.2: Daily life, casual chat, standard routines. (A1-A2 vocabulary)
- TL 1.3 - 1.7: Social issues, professional work, academic study, intermediate lifestyle. (B1-B2 vocabulary)
- TL 1.8 - 2.0: Industry-specific discussions, complex operations, business strategies, intellectual discussions, specialized academia. (B2-C1 vocabulary, highly advanced professional/academic communication)
***ABSOLUTE RULE FOR HIGH TL (>= 1.8):***
1. You are FORBIDDEN from generating casual, daily-life, or basic interpersonal scenarios.
2. The language MUST be formal, academic, or professional.
3. You MUST use sophisticated English vocabulary (B2/C1 level) appropriate for the topic, but it MUST sound natural in real-world professional or intellectual communication. DO NOT use obscure, archaic, or bizarrely low-frequency C2 words that nobody actually uses.
-------------------------------
Target Voltage (U): ${targetU}
Sentence Length Constraints ("${currentLen}"):
- STRICTLY EXACTLY ${targetSentences} sentence(s) (if "Very Short", exactly 1 short sentence).
- Total word count MUST be STRICTLY between ${minWords} and ${targetWords + 5} words. Do NOT generate less than ${minWords} words.
Color Preferences: ${colorPreferences.join(", ")}

Available Ingredients (Resources):
${JSON.stringify(resourceList)}

*** CRITICAL RULES FOR HINTS ***
1. The 'hint' (if provided) is STRICTLY for the English translation ('engSentence').
2. Do NOT insert the English 'hint' directly into the Vietnamese sentence. The Vietnamese sentence MUST ONLY use the natural Vietnamese word.
3. For example, if the Resource is 'Chị Hằng' and the Hint is 'The Moon Lady':
   - Correct vieSentence: "Giảng viên phân tích hình tượng Chị Hằng."
   - Correct engSentence: "The lecturer analyzed the image of The Moon Lady."
   - INCORRECT vieSentence: "Giảng viên phân tích hình tượng The Moon Lady." (DO NOT do this!)

Physics Logic:
${physicsLogic}
- U = Complexity Multiplier * R_total.

Construction Flow:
1. Resource Selection: Pick 2-4 resources that mathematically approach the Target U.
2. ABSOLUTE PRIORITY (Meaning & Logic): The generated sentence MUST be highly natural, logical, and meaningful in everyday conversation. Do NOT forcibly combine incompatible phrases just to meet constraints. If the combination sounds awkward, change the context or pick different resources. It must sound like native speech.
3. Vietnamese First Draft: Think deeply and construct a logical, highly natural Vietnamese sentence (or paragraph, reflecting the Sentence Length constraint) encompassing the selected resources. Frame the sentence completely in natural Vietnamese without English hints.
4. English Translation: Translate that Vietnamese concept into natural English. Apply the 'hint' here to translate specific terminology.
5. Evaluation: SELF-CRITIQUE the sentence. Does it make sense? Is the length exactly ${targetSentences} sentences and the Vietnamese word count strictly between ${minWords}-${targetWords} words? If not, REGENERATE before outputting.
6. Final Validation: Ensure all resources used are from the provided list.
7. Classification: Assign a specific thematic "category" string. Ensure the category explicitly reflects the TL tier (e.g. "Supply Chain Management" for TL 1.7). A casual context for a high TL is a critical failure. It MUST be extremely concise (Maximum 3-5 words), do NOT generate long descriptive phrases.

Output strictly as JSON array:
[
  {
    "engSentence": "...",
    "vieSentence": "...",
    "category": "...",
    "resourcesUsed": [...],
    "rTotal": 12.5,
    "iValue": 1.2,
    "uTotal": 15.0,
    "difficultyLabel": "...",
    "evaluation": "Passed: Natural and meaningful."
  }
]
`;

  const responseText = await callAI(prompt, settings);
  if (!responseText || !responseText.trim()) {
    throw new Error(
      "AI returned an empty response. This may be due to safety filters blocking the content or an API error.",
    );
  }
  const cleanText = cleanJSON(responseText);

  try {
    let results = JSON.parse(cleanText);

    // If AI returned a single object instead of an array, wrap it
    if (!Array.isArray(results)) {
      if (typeof results === "object" && results !== null) {
        // Sometimes AI wraps the array in an object like { "chunks": [...] }
        const possibleArray = Object.values(results).find((v) =>
          Array.isArray(v),
        );
        if (possibleArray) {
          results = possibleArray;
        } else {
          results = [results];
        }
      } else {
        throw new Error("Parsed JSON is neither an object nor an array.");
      }
    }

    // Filter out any that failed internal AI evaluation if the AI was honest
    return (results as (AutoGeneratedChunk & { evaluation?: string })[]).filter(
      (r) => !r.evaluation || r.evaluation.toLowerCase().includes("pass"),
    );
  } catch (e) {
    console.error("Failed to parse AI response:", cleanText);
    throw new Error(
      `AI returned invalid JSON format: ${e instanceof Error ? e.message : "Unknown error"}. Response was: ${cleanText.substring(0, 100)}...`,
    );
  }
}
