import { GoogleGenAI } from "@google/genai";
import { Resource, ColorCategory, AISettings, SentenceLength } from "../types";

// We lazily instantiate the Gemini client to avoid startup crashes if the key is completely missing
function getGeminiClient(customKey?: string) {
  const key = customKey || process.env.GEMINI_API_KEY;
  if (!key) {
    throw new Error(
      "No Gemini API Key available. Please specify an API key in your AI Configuration.",
    );
  }
  return new GoogleGenAI({ apiKey: key });
}

export interface GenerateChunkParams {
  resources: Resource[];
  rTotal: number;
  iValue: number;
  uTotal: number;
  theme?: string;
  topicLevel?: number;
  sentenceLength?: SentenceLength;
  settings?: AISettings;
}

export interface GeneratedChunkResponse {
  engSentence: string;
  vieSentence: string;
  category: string;
}

export interface AutoGenerateParams {
  theme: string;
  topicLevel?: number;
  targetU: number;
  quantity: number;
  sentenceLength: SentenceLength;
  colorPreferences: ColorCategory[];
  availableResources: Resource[];
  settings?: AISettings;
}

export interface AutoGeneratedChunk extends GeneratedChunkResponse {
  resourcesUsed: Resource[];
  rTotal: number;
  iValue: number;
  uTotal: number;
  difficultyLabel: string;
  audioUrl?: string | null;
}

export interface LCBreakdown {
  sentenceCount: number;
  wordCount: number;
  lengthBand: string;
  lcValue: number;
  reasoning: string;
}

export interface TCBreakdown {
  matchedResources: any[];
  candidateResources: any[];
  confirmedTC: number;
  estimatedTC: number;
  calculation: string;
}

export interface TLBreakdown {
  band: string;
  tlValue: number;
  confidence: number;
  reasoning: string;
}

export interface CVRResult {
  transcriptRaw: string;
  transcriptNormalized: string;
  lcBreakdown: LCBreakdown;
  tcBreakdown: TCBreakdown;
  tlBreakdown: TLBreakdown;
  predictedCVR: number;
  formula: string;
  calculationString: string;
}

export async function transcribeAudio(
  audioBlob: Blob,
  settings?: AISettings,
): Promise<string> {
  const base64Audio = await new Promise<string>((resolve, reject) => {
    const reader = new FileReader();
    reader.onloadend = () => {
      const base64 = (reader.result as string).split(",")[1];
      resolve(base64);
    };
    reader.onerror = reject;
    reader.readAsDataURL(audioBlob);
  });

  const apiKey = settings?.geminiApiKey || process.env.GEMINI_API_KEY;
  const aiClient = getGeminiClient(apiKey);
  const modelToUse = settings?.audioTranscriptModel || "gemini-2.5-flash";

  const response = await aiClient.models.generateContent({
    model: modelToUse,
    contents: [
      {
        inlineData: {
          mimeType: audioBlob.type || "audio/webm",
          data: base64Audio,
        },
      },
      "Please transcribe this audio. Return ONLY the transcript text in the language spoken, with no other commentary, quotes, or formatting.",
    ],
  });
  return response.text ? response.text.trim() : "";
}

export async function measureCVR(
  transcript: string,
  settings?: AISettings,
  baseOhms?: Record<string, number>,
  resources?: Resource[],
  tcCorrections?: Array<{sentence_fragment: string, resource_name: string, color: string, ohm: number}>,
): Promise<CVRResult> {
  const rawOhms = settings?.ohmBaseValues ||
    baseOhms || { Green: 5, Blue: 7, Red: 9, Pink: 3 };
  
  // Normalize to uppercase for easier AI matching
  const r = rawOhms as Record<string, number>;
  const ohms: Record<string, number> = {
    GREEN: Number(r.Green || r.GREEN || 5),
    BLUE: Number(r.Blue || r.BLUE || 7),
    RED: Number(r.Red || r.RED || 9),
    PINK: Number(r.Pink || r.PINK || 3),
  };

  // Strip punctuation and extra spaces for robust matching against transcript typos
  const stripPunctuation = (str: string) =>
    str
      .toLowerCase()
      .replace(/[\s\u200B-\u200D\uFEFF]+/g, " ")
      .replace(/[.,!?;:"\\'(){}\[\]<>—\-]/g, "")
      .trim();
  const trStripped = stripPunctuation(transcript);

  // Find matched resources using stripped text
  const matched: any[] = [];

  if (resources && resources.length > 0) {
    resources.forEach((r) => {
      // Split by " / " first — resource names use this as an alternative-phrase separator
      // e.g. "Phiền thiệt!,... / Thiệt là phiền toái,..." → two separate phrases to try
      const alternatives = r.name.split(/ \/ /);

      let isMatch = false;

      for (const alt of alternatives) {
        if (isMatch) break;

        const cleaned = alt.replace(/\.{2,}|…/g, " ").trim();
        const wordsArr = cleaned.split(/\s+/).filter((w) => w.length > 0);
        let variations: string[][] = [[]];

        for (const word of wordsArr) {
          if (word.includes("/")) {
            // Inline slash: "Ai/đứa" → each side is a separate variant
            const parts = word.split("/");
            const newVars: string[][] = [];
            for (const part of parts) {
              if (part && part.trim() !== "") {
                for (const v of variations) {
                  newVars.push([...v, part]);
                }
              }
            }
            if (newVars.length > 0) {
              variations = newVars;
            }
          } else {
            for (const v of variations) {
              v.push(word);
            }
          }
        }

        const textVariations = variations
          .map((vArr) => stripPunctuation(vArr.join(" ")).trim())
          .filter((v) => v.length > 0);

        textVariations.push(stripPunctuation(alt.replace(/\//g, " ")).trim());

        const uniqueVars = Array.from(new Set(textVariations));

        for (const v of uniqueVars) {
          const vWordCount = v ? v.split(/\s+/).length : 0;
          // Skip single-word matches for complex single-alternative resources
          if (v && vWordCount === 1 && r.name.trim().split(/[\s/]+/).length >= 3) continue;
          // Skip ≤2-word alternatives from multi-alternative resources (e.g. "Yên tâm" from "Yên chí! / Yên tâm!,...")
          if (v && vWordCount <= 2 && alternatives.length > 1) continue;

          if (v && (" " + trStripped + " ").includes(" " + v + " ")) {
            isMatch = true;
            break;
          }
        }
      }

      if (isMatch) {
        matched.push({
          text: r.name,
          color: r.color,
          ohm: r.ohm,
        });
      }
    });
  }

  const confirmedTC = matched.reduce((acc, curr) => acc + curr.ohm, 0);

  const matchedStr =
    matched.length > 0
      ? `\n\nCác resources đã match sẵn trong thư viện (Confirmed TC = ${confirmedTC}):\n` +
        matched.map((m) => `- "${m.text}" (${m.color} ${m.ohm}Ω)`).join("\n")
      : `\n\nKhông có resources nào trong thư viện match với đoạn Transcript. (Confirmed TC = 0)`;

  const correctionsStr =
    tcCorrections && tcCorrections.length > 0
      ? `\n\n## Lịch sử Corrections đã xác nhận (ưu tiên tham khảo khi gặp cụm từ tương tự):\n` +
        tcCorrections.slice(0, 20).map((c) => `- "${c.sentence_fragment}" → ${c.color} ${c.ohm}Ω`).join("\n")
      : "";

  const multipliers = settings?.complexityMultipliers || {
    "Very Short": 1,
    Short: 1.5,
    Medium: 2,
    Long: 2.5,
  };
  const constraints = settings?.sentenceConstraints || {
    "Very Short": { maxSentences: 1, maxWords: 15 },
    Short: { maxSentences: 2, maxWords: 30 },
    Medium: { maxSentences: 3, maxWords: 60 },
    Long: { maxSentences: 5, maxWords: 100 },
  };

  // 1. Calculate LC Deterministically (Strict Words Buckets)
  const sentences =
    transcript.split(/[.?!]+/).filter((s) => s.trim().length > 0).length || 1;
  const words =
    transcript.split(/\s+/).filter((w) => w.trim().length > 0).length || 0;

  let selectedBand: SentenceLength = "Long";

  const vsMaxWords = Number(constraints["Very Short"]?.maxWords) || 15;
  const sMaxWords = Number(constraints["Short"]?.maxWords) || 30;
  const mMaxWords = Number(constraints["Medium"]?.maxWords) || 60;
  const lMaxWords = Number(constraints["Long"]?.maxWords) || 100;

  // We are evaluating based strictly on word counts as requested
  if (words <= vsMaxWords) {
    selectedBand = "Very Short";
  } else if (words <= sMaxWords) {
    selectedBand = "Short";
  } else if (words <= mMaxWords) {
    selectedBand = "Medium";
  } else {
    selectedBand = "Long";
  }

  const lcValue = multipliers[selectedBand] || 1;

  const reasoningString = `Determined by engine constraints (Words mode). The transcript has ${words} words. The configured bounds are: Very Short (≤${vsMaxWords}), Short (≤${sMaxWords}), Medium (≤${mMaxWords}), Long (>${mMaxWords}). Because ${words} falls into the ${selectedBand} bucket, it was classified as ${selectedBand} (Multiplier: ${lcValue}).`;

  const defaultInstructions = `
Bạn là CVR Measure Engine. Nhiệm vụ của bạn là phân tích đoạn Transcript tiếng Việt để tìm ra độ khó (CVR) dựa trên 3 yếu tố:

1. TC (Total Resource Ohm load): Bóc tách các cụm từ (trừ các từ ngữ đã match ở trên) làm Resource Candidates.
   --- STRICT VOCABULARY MAPPING RULES ---
   - PINK (${ohms.PINK}Ω): Thuật ngữ then chốt hoặc danh từ cốt lõi (Key Concepts / Technical Terms). Từ vựng mang tính kỹ thuật hoặc định danh cụ thể. Phải từ B1 trở lên — từ quá phổ thông không được xếp PINK. Ví dụ: Dép lào, Ví điện tử.
   - GREEN (${ohms.GREEN}Ω): Từ đệm, từ nối hoặc từ điều hướng (Discourse Markers / Fillers / Conditioners). Dùng để định hướng câu nói, tạo sự tự nhiên hoặc làm mềm ngữ cảnh. Ví dụ: Tin tui đi, Thành thật mà nói, Nói chung là.
   - BLUE (${ohms.BLUE}Ω): Khung câu hoặc cấu trúc ngữ pháp (Sentence Frames / Grammatical Skeletons). Các cấu trúc chờ được lấp đầy nội dung. Ví dụ: Cậu nên nhớ rằng..., Tui không ngờ là..., Vấn đề không phải là....
   - RED (${ohms.RED}Ω): Thành ngữ, ẩn dụ hoặc cách diễn đạt hình ảnh (Idioms / Metaphors / Vivid Expressions). Không mang nghĩa đen, độ phức tạp ngữ nghĩa và văn hóa cao nhất. Ví dụ: Mật ngọt chết ruồi, Cậu tới số rồi, Vắt chân lên cổ.
   *QUAN TRỌNG: Phân loại theo chức năng ngôn ngữ của cụm từ trong câu, không phải theo độ phổ biến của từ đơn lẻ.*

   - Tính Confirmed TC = Tổng Ohm của các resources đã match.
   - Tính Estimated TC = Confirmed TC + Tổng Ohm của các Resource Candidates.
2. LC (Length-Complexity): Đã được tính toán bằng Engine: ${sentences} câu, ${words} từ => Band: ${selectedBand}, Multiplier: ${lcValue}. Không cần tính lại.
3. TL (Topic/Vocabulary Level): Đánh giá toàn bộ câu và chủ đề trên rải điểm 1.0 đến 2.0 (bước 0.1).

   *** ĐIỂM 1.0 LÀ CÓ THẬT — PHẢI DÙNG khi câu đủ điều kiện, KHÔNG được dùng 1.2 như một "điểm an toàn mặc định" ***

   - A1 (1.0): Câu sinh hoạt thuần túy, hành động/sự kiện thường ngày, KHÔNG có sắc thái cảm xúc phức tạp, KHÔNG ẩn dụ, KHÔNG thành ngữ, từ vựng đơn giản nhất.
     → VÍ DỤ bắt buộc cho 1.0: "Sao giờ mới tới?", "Mọi người đợi từ sáng, cậu ngủ quên rồi.", "Ra công viên chơi cầu tuột.", "Hôm nay tan làm muộn nên đi thang máy."
   - A2 (1.1-1.2): Hàng ngày nhưng có thêm một chút biểu cảm đơn giản hoặc từ kép phổ biến. Chỉ dùng 1.2 nếu câu CÓ yếu tố này, không phải mặc định.
   - B1-B2 (1.3-1.7): Chủ đề xã hội, công việc, gia đình phức tạp, cảm xúc đa chiều, từ vựng đa dạng.
     *** ĐẶC BIỆT: Câu NGẮN nhưng có ẩn dụ, hình ảnh tinh tế, hoặc ngụ ý cảm xúc sâu → vẫn phải cho 1.5-1.7. ***
     → VÍ DỤ: "Ánh mắt mẹ nói rằng không cần nhiều lời nữa." = 1.7 (ẩn dụ "ánh mắt nói"), không phải 1.2.
   - B2-C1 (1.8-2.0): Học thuật, chuyên ngành hẹp, từ hán việt hiếm gặp, thuật ngữ kỹ thuật/pháp lý/y khoa.
     *Điểm 1.8-2.0 RẤT KHÓ đạt — chỉ dùng khi câu mang đậm tính học thuật hoặc chuyên ngành sâu.*

   RULE: Nếu câu chỉ mô tả hành động/sự việc hàng ngày không có tầng nghĩa ẩn hay từ vựng phức tạp → PHẢI cho 1.0, không phải 1.1 hay 1.2.

Công thức cuối: CVR = Estimated TC * LC * TL.
`;

  const systemInstructions = defaultInstructions;

  const prompt = `
${systemInstructions}

Transcript:
"${transcript}"
${matchedStr}${correctionsStr}

Return the result STRICTLY as a JSON object with this structure:
{
  "transcriptRaw": "...",
  "transcriptNormalized": "...",
  "lcBreakdown": {
    "sentenceCount": ${sentences},
    "wordCount": ${words},
    "lengthBand": "${selectedBand}",
    "lcValue": ${lcValue},
    "reasoning": "Determined by Engine constraints."
  },
  "tcBreakdown": {
    "matchedResources": [ ${matched.length > 0 ? `{"text": "${matched[0].text}", "color": "${matched[0].color}", "ohm": ${matched[0].ohm}}` : ""} ],
    "candidateResources": [
      {
         "text": "cụm từ 1",
         "color": "RED",
         "ohm": ${ohms.RED},
         "confidence": 0.9,
         "reasoning": "..."
      }
    ],
    "confirmedTC": ${confirmedTC},
    "estimatedTC": ${confirmedTC},
    "calculation": "${confirmedTC} (Confirmed) + ..."
  },
  "tlBreakdown": {
    "band": "A1-A2",
    "tlValue": 1.0,
    "confidence": 0.9,
    "reasoning": "TL value is influenced by the difficult matched and candidate vocab..."
  },
  "predictedCVR": ${confirmedTC * lcValue * 1.0},
  "formula": "Estimated TC * LC * TL",
  "calculationString": "..."
}
`;

  const responseText = await callAI(prompt, settings);
  try {
    const jsonMatch =
      responseText.match(/```json\n([\s\S]*?)\n```/) ||
      responseText.match(/\{[\s\S]*\}/);
    const jsonString = jsonMatch ? jsonMatch[1] || jsonMatch[0] : responseText;
    const result = JSON.parse(jsonString) as CVRResult;

    // Force Deterministic LC overwrite to prevent hallucinations
    result.lcBreakdown = {
      sentenceCount: sentences,
      wordCount: words,
      lengthBand: selectedBand,
      lcValue: lcValue,
      reasoning: reasoningString,
    };

    // Normalize and Enforce Candidate Ohms based on settings
    const rawCandidates = result.tcBreakdown.candidateResources || [];
    const forcedCandidates = rawCandidates.map((c: any) => {
      const color = (c.color || "").toUpperCase();
      const enforcedOhm = ohms[color] || 0;
      return {
        ...c,
        color: color.charAt(0) + color.slice(1).toLowerCase(), // Normalize back to 'Red', 'Green', etc.
        ohm: enforcedOhm,
        type: "candidate",
      };
    });

    // Force Deterministic TC accumulation with capping!
    result.tcBreakdown.matchedResources = matched;

    const maxResourcesPerBand: Record<SentenceLength, number> = {
      "Very Short": 1,
      Short: 2,
      Medium: 3,
      Long: 4,
    };

    const maxAllowedResources = maxResourcesPerBand[selectedBand] || 4;

    const allResources = [
      ...matched.map((m) => ({ ...m, type: "matched" })),
      ...forcedCandidates,
    ];

    allResources.sort((a, b) => {
      // Prioritize matched resources
      if (a.type === "matched" && b.type !== "matched") return -1;
      if (a.type !== "matched" && b.type === "matched") return 1;
      // If same type, sort by ohm descending
      return b.ohm - a.ohm;
    });

    const includedResources = allResources.slice(0, maxAllowedResources);
    const overflowResources = allResources.slice(maxAllowedResources);

    const includedTC = includedResources.reduce(
      (acc, curr) => acc + curr.ohm,
      0,
    );

    result.tcBreakdown.confirmedTC = matched.reduce(
      (acc, curr) => acc + curr.ohm,
      0,
    );
    result.tcBreakdown.candidateResources = forcedCandidates;
    result.tcBreakdown.estimatedTC = includedTC;

    let calcStr = includedResources
      .map((r) => `${r.ohm} (${r.type})`)
      .join(" + ");
    if (overflowResources.length > 0) {
      calcStr += ` ... [+${overflowResources.length} overflow item(s) ignored]`;
    }
    if (includedResources.length === 0) calcStr = "0";

    result.tcBreakdown.calculation = `${calcStr} = ${includedTC} (Capped at ${maxAllowedResources} slots for ${selectedBand})`;

    // Recalculate exactly CVR
    result.tlBreakdown.tlValue =
      Math.round(result.tlBreakdown.tlValue * 10) / 10;
    const finalCVR =
      result.tcBreakdown.estimatedTC *
      result.lcBreakdown.lcValue *
      result.tlBreakdown.tlValue;
    result.predictedCVR = Math.round(finalCVR);
    result.calculationString = `${result.tcBreakdown.estimatedTC} (TC) × ${result.lcBreakdown.lcValue} (LC) × ${result.tlBreakdown.tlValue} (TL) = ${result.predictedCVR}`;

    return result;
  } catch (error) {
    console.error("Failed to parse analysis result:", responseText);
    throw new Error("Failed to parse analysis result from AI.");
  }
}

export async function fetchOpenRouterModels(
  apiKey: string,
  endpoint: string = "https://openrouter.ai/api/v1",
) {
  if (!apiKey) return [];
  try {
    const response = await fetch(
      `${endpoint.replace(/\/+$/, "")}/models`,
      {
        method: "GET",
        headers: {
          Authorization: `Bearer ${apiKey}`,
          "HTTP-Referer": window.location.origin,
          "X-Title": "CHUNKS CVR",
        },
      },
    );
    if (!response.ok)
      throw new Error(`Failed to fetch models: ${response.statusText}`);
    const data = await response.json();
    return data.data || [];
  } catch (error) {
    console.error("Error fetching models:", error);
    throw error;
  }
}

async function callAI(prompt: string, settings?: AISettings): Promise<string> {
  const apiKey = settings?.apiKey;
  const primaryModel = settings?.primaryModel || "gemini-2.0-flash";
  const fallbackModel = settings?.fallbackModel || "gemini-1.5-flash";

  // If no custom API key is provided, we use the default Gemini client with the configured model
  if (!apiKey) {
    try {
      const gClient = getGeminiClient();
      const response = await gClient.models.generateContent({
        model: primaryModel,
        contents: prompt,
        config: {
          responseMimeType: "application/json",
        },
      });
      if (response.text) return response.text;
    } catch (error) {
      console.warn(
        `Default model ${primaryModel} failed, trying fallback ${fallbackModel}:`,
        error,
      );
      const gClient = getGeminiClient();
      const response = await gClient.models.generateContent({
        model: fallbackModel,
        contents: prompt,
        config: {
          responseMimeType: "application/json",
        },
      });
      if (!response.text) throw new Error("No response from Gemini fallback");
      return response.text;
    }
    throw new Error("Failed to get response from Gemini");
  }

  const { endpoint } = settings;
  const modelsToTry = [primaryModel, fallbackModel].filter(Boolean);
  let lastError = null;

  // ⚠️ Detect Mixed Content early: HTTP endpoint on HTTPS page will always be blocked by browser
  const rawEndpoint = (endpoint || "https://openrouter.ai/api/v1").trim();
  if (window.location.protocol === "https:" && rawEndpoint.startsWith("http:")) {
    throw new Error(
      `Mixed Content Error: Trang web chạy HTTPS nhưng endpoint đang dùng HTTP (${rawEndpoint}). Browser sẽ block request này.\n\n` +
      `Giải pháp:\n` +
      `1. Dùng endpoint HTTPS (nếu server hỗ trợ SSL)\n` +
      `2. Hoặc cấu hình reverse proxy HTTPS → HTTP trên server\n` +
      `3. Hoặc dùng OpenRouter (https://openrouter.ai/api/v1) với API key`
    );
  }

  for (const model of modelsToTry) {
    try {
      const targetEndpoint = rawEndpoint;
      const chatEndpoint = `${targetEndpoint.replace(/\/+$/, "")}/chat/completions`;

      const response = await fetch(chatEndpoint, {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
          Authorization: `Bearer ${apiKey}`,
          "HTTP-Referer": window.location.origin,
          "X-Title": "CHUNKS CVR",
        },
        body: JSON.stringify({
          model: model,
          messages: [{ role: "user", content: prompt }],
          stream: false,
        }),
      });

      if (!response.ok) {
        const errorData = await response.json().catch(() => ({}));
        let errorMessage =
          errorData.error?.message || errorData.error || errorData.message;

        if (!errorMessage && errorData.rawResponse) {
          // Extract text from HTML if it's a Cloudflare error page
          const raw = errorData.rawResponse;
          if (raw.includes("<html") && raw.includes("530")) {
            errorMessage =
              "API Error 530: Cloudflare DNS/Origin error. The AI endpoint might be down or misconfigured.";
          } else {
            errorMessage = `API Error ${response.status}: ${raw.substring(0, 100)}...`;
          }
        }

        errorMessage = errorMessage || `API Error: ${response.status}`;
        throw new Error(
          typeof errorMessage === "string"
            ? errorMessage
            : JSON.stringify(errorMessage),
        );
      }

      const data = await response.json();

      // Handle OpenAI format
      if (data.choices && data.choices.length > 0 && data.choices[0].message) {
        return data.choices[0].message.content;
      }
      // Handle Ollama native format
      if (data.response) {
        return data.response;
      }
      // Handle Anthropic format
      if (data.content && Array.isArray(data.content)) {
        return data.content[0].text;
      }
      // Handle raw text fallback from our proxy
      if (data.rawResponse) {
        // Check if it looks like Server-Sent Events (SSE)
        if (
          typeof data.rawResponse === "string" &&
          data.rawResponse.includes("data: {") &&
          data.rawResponse.includes('"choices"')
        ) {
          let fullContent = "";
          const lines = data.rawResponse.split("\n");
          for (const line of lines) {
            if (line.startsWith("data: ") && line !== "data: [DONE]") {
              try {
                const chunk = JSON.parse(line.substring(6));
                if (
                  chunk.choices &&
                  chunk.choices[0] &&
                  chunk.choices[0].delta &&
                  chunk.choices[0].delta.content
                ) {
                  fullContent += chunk.choices[0].delta.content;
                }
              } catch (e) {
                // Ignore parse errors for individual lines
              }
            }
          }
          if (fullContent) return fullContent;
        }
        return data.rawResponse;
      }

      // If we don't know the format, throw an error with the stringified data so the user can see it
      throw new Error(
        `Unexpected API response format: ${JSON.stringify(data).substring(0, 200)}...`,
      );
    } catch (error) {
      console.warn(`Failed with model ${model}:`, error);
      lastError = error;
    }
  }

  // All custom models failed — throw the real error so the user can see what went wrong.
  // We intentionally do NOT silently fall back to Gemini here, because:
  //  - The user has configured a custom endpoint/model; Gemini is not expected.
  //  - Silently falling back to Gemini with no key produces a confusing "No Gemini API Key" error
  //    that obscures the real problem (wrong endpoint, Mixed Content, bad model name, etc.).
  const errorMsg = lastError instanceof Error ? lastError.message : String(lastError);
  throw new Error(
    `Tất cả models đã thất bại.\n\n` +
    `• Primary model: "${primaryModel}"\n` +
    `• Fallback model: "${fallbackModel}"\n` +
    `• Endpoint: "${rawEndpoint}"\n\n` +
    `Lỗi cuối: ${errorMsg}\n\n` +
    `Kiểm tra lại:\n` +
    `1. Model name đúng format (vd: openai/gpt-4o, anthropic/claude-3-haiku)\n` +
    `2. Endpoint phải HTTPS nếu site chạy HTTPS\n` +
    `3. API Key còn hạn và đúng quyền`
  );
}

function cleanJSON(text: string): string {
  if (!text) return "";
  let cleanText = text.trim();

  // Try to extract JSON block if markdown is used
  const jsonMatch = cleanText.match(/```(?:json)?\s*([\s\S]*?)\s*```/);
  if (jsonMatch && jsonMatch[1]) {
    return jsonMatch[1].trim();
  }

  // Fallback: try to find the first [ or { and last ] or }
  const firstBrace = cleanText.indexOf("{");
  const lastBrace = cleanText.lastIndexOf("}");
  const firstBracket = cleanText.indexOf("[");
  const lastBracket = cleanText.lastIndexOf("]");

  // Determine if it's an array or object based on what comes first
  const hasBracket = firstBracket !== -1 && lastBracket !== -1;
  const hasBrace = firstBrace !== -1 && lastBrace !== -1;

  if (hasBracket && (!hasBrace || firstBracket < firstBrace)) {
    return cleanText.substring(firstBracket, lastBracket + 1);
  } else if (hasBrace) {
    return cleanText.substring(firstBrace, lastBrace + 1);
  }

  return cleanText;
}

export async function generateChunk(
  params: GenerateChunkParams,
): Promise<GeneratedChunkResponse> {
  const {
    resources,
    rTotal,
    iValue,
    uTotal,
    settings,
    theme,
    topicLevel,
    sentenceLength,
  } = params;
  const resourceList = resources
    .map(
      (r) =>
        `${r.name} (${r.color}, ${r.ohm} Ohm${r.hint ? `, Context Hint: ${r.hint}` : ""})`,
    )
    .join(", ");

  const currentLen = sentenceLength || "Medium";
  const constraints = settings?.sentenceConstraints?.[currentLen];

  const targetSentences =
    constraints?.maxSentences ||
    (currentLen === "Very Short"
      ? 1
      : currentLen === "Short"
        ? 2
        : currentLen === "Medium"
          ? 3
          : 5);
  const targetWords =
    constraints?.maxWords ||
    (currentLen === "Very Short"
      ? 15
      : currentLen === "Short"
        ? 30
        : currentLen === "Medium"
          ? 60
          : 100);
  const minWords = Math.max(5, Math.floor(targetWords * 0.8));

  const prompt = `
You are an expert linguist and curriculum designer for an EdTech system called "CHUNKS".
Your task is to generate a bilingual sentence (Vietnamese first, then English) based on a set of input resources and a specific algorithm.

Target Theme/Topic: ${theme === "INFER_FROM_RESOURCES" ? "Dynamically infer the most logical and specific theme entirely based on the provided Input Resources. Do NOT use a random theme." : theme ? theme : "Dynamically formulate a random specific theme that completely aligns with the STRICT TL MAPPING RULES below. Do not be generic."}
Topic Level (TL target): ${topicLevel || 1.0}
--- STRICT TL MAPPING RULES ---
- TL 1.0 - 1.2: Daily life, casual chat, standard routines. (A1-A2 vocabulary)
- TL 1.3 - 1.7: Social issues, professional work, academic study, intermediate lifestyle. (B1-B2 vocabulary)
- TL 1.8 - 2.0: Industry-specific discussions, complex operations, business strategies, intellectual discussions, specialized academia. (B2-C1 vocabulary, highly advanced professional/academic communication)
***ABSOLUTE RULE FOR HIGH TL (>= 1.8):***
1. You are FORBIDDEN from generating casual, daily-life, or basic interpersonal scenarios.
2. The language MUST be formal, academic, or professional.
3. You MUST use sophisticated English vocabulary (B2/C1 level) appropriate for the topic, but it MUST sound natural in real-world professional or intellectual communication. DO NOT use obscure, archaic, or bizarrely low-frequency C2 words that nobody actually uses.
-------------------------------
Desired Sentence Length: ${currentLen}

Algorithm Context:
- U = I * R
- R (Resistance): Base difficulty of resources. Total R = ${rTotal}
- I (Current/MSE): Context/complexity variable. I = ${iValue}
- U (Voltage): Total lesson energy/difficulty. U = ${uTotal}

Input Resources to include in the sentence:
${resourceList}

*** CRITICAL RULES FOR HINTS ***
1. The 'Context Hint' (if provided) is STRICTLY for the English translation ('engSentence').
2. Do NOT insert the English 'Context Hint' directly into the Vietnamese sentence. The Vietnamese sentence MUST ONLY use the natural Vietnamese word.
3. For example, if the Resource is 'Chị Hằng' and the Hint is 'The Moon Lady':
   - Correct vieSentence: "Giảng viên phân tích hình tượng Chị Hằng."
   - Correct engSentence: "The lecturer analyzed the image of The Moon Lady."
   - INCORRECT vieSentence: "Giảng viên phân tích hình tượng The Moon Lady." (DO NOT do this!)

Instructions:
1. ABSOLUTE PRIORITY (Meaning & Logic): The final result MUST be a highly natural, logical, and meaningful sentence/paragraph in real-life context. Do NOT force words together if they create a nonsensical "Frankenstein" sentence. It MUST sound like something a native speaker would actually say in real conversation.
2. Vietnamese First: Start by constructing a logical Vietnamese scenario encompassing the exact meaning of all input resources. Frame the sentence completely in natural Vietnamese. Do NOT insert any English words from the hints into the Vietnamese sentence.
3. English Translation: Translate that Vietnamese concept into a natural-sounding English equivalent. This is where you apply the 'Context Hint' to translate specific terminology. The English version must carry the same semantic integrity and clear intent.
4. Length Calibration: Strictly follow the length constraints for "${currentLen}"! Calculate the word count based on the VIETNAMESE sentence.
   - You MUST generate EXACTLY ${targetSentences} sentence(s) (if "Very Short", exactly 1 small sentence).
   - The total Vietnamese word count MUST be STRICTLY between ${minWords} and ${targetWords} words. Your sentence should ideally be close to ${targetWords} words, but absolutely NOT less than ${minWords}.
5. Theme Adherence: The context MUST strictly revolve around the requested theme. If no theme is provided, dynamically formulate a specific, highly relevant theme that matches the STRICT TL MAPPING RULES. A casual context for a high TL is a critical failure.
6. Energy Level: The structural complexity and vocabulary choice should reflect the U (Voltage) value: ${uTotal}. Higher U means more sophisticated grammar and nuanced meaning.
7. Classification: Assign a specific thematic category. Ensure the category explicitly reflects the TL tier (e.g. "Supply Chain Management" for TL 1.7, not "General Conversation"). It MUST be extremely concise (Maximum 3-5 words), do NOT generate long descriptive phrases.
8. Output Format: Return ONLY JSON. Ensure the final output is meaningful and accurately uses the input parameters.

Output MUST be strictly in the following JSON format:
{
  "engSentence": "...",
  "vieSentence": "...",
  "category": "...",
  "evaluation": "Explanation of how the resources create a meaningful context matching the U: ${uTotal}"
}
`;
  const responseText = await callAI(prompt, settings);
  if (!responseText || !responseText.trim()) {
    throw new Error(
      "AI returned an empty response. This may be due to safety filters blocking the content or an API error.",
    );
  }
  const cleanText = cleanJSON(responseText);

  try {
    return JSON.parse(cleanText) as GeneratedChunkResponse & {
      evaluation?: string;
    };
  } catch (e) {
    console.error("Failed to parse AI response:", cleanText);
    throw new Error(
      `AI returned invalid JSON format: ${e instanceof Error ? e.message : "Unknown error"}. Response was: ${cleanText.substring(0, 100)}...`,
    );
  }
}

export async function generateAutoChunks(
  params: AutoGenerateParams,
): Promise<AutoGeneratedChunk[]> {
  const {
    theme,
    topicLevel,
    targetU,
    quantity,
    sentenceLength,
    colorPreferences,
    availableResources,
    settings,
  } = params;

  const currentLen = sentenceLength || "Medium";
  const constraints = settings?.sentenceConstraints?.[currentLen];
  const targetSentences =
    constraints?.maxSentences ||
    (currentLen === "Very Short"
      ? 1
      : currentLen === "Short"
        ? 2
        : currentLen === "Medium"
          ? 3
          : 5);
  const targetWords =
    constraints?.maxWords ||
    (currentLen === "Very Short"
      ? 15
      : currentLen === "Short"
        ? 30
        : currentLen === "Medium"
          ? 60
          : 100);
  const minWords = Math.max(5, Math.floor(targetWords * 0.8));

  // Pre-filter resources to balance them based on color preferences and target U
  const filteredAvailable = availableResources
    .filter(
      (r) =>
        colorPreferences.length === 0 || colorPreferences.includes(r.color),
    )
    .sort(
      (a, b) => Math.abs(a.ohm - targetU / 3) - Math.abs(b.ohm - targetU / 3),
    ) // Heuristic: try to find resources that are roughly 1/3 of target U
    .slice(0, 150);

  const resourceList = filteredAvailable.map((r) => ({
    id: r.id,
    name: r.name,
    color: r.color,
    ohm: r.ohm,
    hint: r.hint,
  }));

  const formulaType = settings?.formulaType || "sum";
  const physicsLogic =
    formulaType === "sum"
      ? `- R_total = Sum of all individual resource Ohms (R1 + R2 + R3 + ...). (Example: 5 + 9 + 3 = 17)`
      : `- R_total = Sum(R) for same-color series, then Product of those sums for different colors.`;

  const prompt = `
You are a Master Linguistic Architect for the "CHUNKS" EdTech system.
Your mission is to construct ${quantity} high-quality learning chunks.

Theme: ${theme ? theme : "Determine dynamically based on Topic Level (TL)"}
Topic Level (TL target): ${topicLevel || 1.0}
--- STRICT TL MAPPING RULES ---
- TL 1.0 - 1.2: Daily life, casual chat, standard routines. (A1-A2 vocabulary)
- TL 1.3 - 1.7: Social issues, professional work, academic study, intermediate lifestyle. (B1-B2 vocabulary)
- TL 1.8 - 2.0: Industry-specific discussions, complex operations, business strategies, intellectual discussions, specialized academia. (B2-C1 vocabulary, highly advanced professional/academic communication)
***ABSOLUTE RULE FOR HIGH TL (>= 1.8):***
1. You are FORBIDDEN from generating casual, daily-life, or basic interpersonal scenarios.
2. The language MUST be formal, academic, or professional.
3. You MUST use sophisticated English vocabulary (B2/C1 level) appropriate for the topic, but it MUST sound natural in real-world professional or intellectual communication. DO NOT use obscure, archaic, or bizarrely low-frequency C2 words that nobody actually uses.
-------------------------------
Target Voltage (U): ${targetU}
Sentence Length Constraints ("${currentLen}"):
- STRICTLY EXACTLY ${targetSentences} sentence(s) (if "Very Short", exactly 1 short sentence).
- Total word count MUST be STRICTLY between ${minWords} and ${targetWords + 5} words. Do NOT generate less than ${minWords} words.
Color Preferences: ${colorPreferences.join(", ")}

Available Ingredients (Resources):
${JSON.stringify(resourceList)}

*** CRITICAL RULES FOR HINTS ***
1. The 'hint' (if provided) is STRICTLY for the English translation ('engSentence').
2. Do NOT insert the English 'hint' directly into the Vietnamese sentence. The Vietnamese sentence MUST ONLY use the natural Vietnamese word.
3. For example, if the Resource is 'Chị Hằng' and the Hint is 'The Moon Lady':
   - Correct vieSentence: "Giảng viên phân tích hình tượng Chị Hằng."
   - Correct engSentence: "The lecturer analyzed the image of The Moon Lady."
   - INCORRECT vieSentence: "Giảng viên phân tích hình tượng The Moon Lady." (DO NOT do this!)

Physics Logic:
${physicsLogic}
- U = Complexity Multiplier * R_total.

Construction Flow:
1. Resource Selection: Pick 2-4 resources that mathematically approach the Target U.
2. ABSOLUTE PRIORITY (Meaning & Logic): The generated sentence MUST be highly natural, logical, and meaningful in everyday conversation. Do NOT forcibly combine incompatible phrases just to meet constraints. If the combination sounds awkward, change the context or pick different resources. It must sound like native speech.
3. Vietnamese First Draft: Think deeply and construct a logical, highly natural Vietnamese sentence (or paragraph, reflecting the Sentence Length constraint) encompassing the selected resources. Frame the sentence completely in natural Vietnamese without English hints.
4. English Translation: Translate that Vietnamese concept into natural English. Apply the 'hint' here to translate specific terminology.
5. Evaluation: SELF-CRITIQUE the sentence. Does it make sense? Is the length exactly ${targetSentences} sentences and the Vietnamese word count strictly between ${minWords}-${targetWords} words? If not, REGENERATE before outputting.
6. Final Validation: Ensure all resources used are from the provided list.
7. Classification: Assign a specific thematic "category" string. Ensure the category explicitly reflects the TL tier (e.g. "Supply Chain Management" for TL 1.7). A casual context for a high TL is a critical failure. It MUST be extremely concise (Maximum 3-5 words), do NOT generate long descriptive phrases.

Output strictly as JSON array:
[
  {
    "engSentence": "...",
    "vieSentence": "...",
    "category": "...",
    "resourcesUsed": [...],
    "rTotal": 12.5,
    "iValue": 1.2,
    "uTotal": 15.0,
    "difficultyLabel": "...",
    "evaluation": "Passed: Natural and meaningful."
  }
]
`;

  const responseText = await callAI(prompt, settings);
  if (!responseText || !responseText.trim()) {
    throw new Error(
      "AI returned an empty response. This may be due to safety filters blocking the content or an API error.",
    );
  }
  const cleanText = cleanJSON(responseText);

  try {
    let results = JSON.parse(cleanText);

    // If AI returned a single object instead of an array, wrap it
    if (!Array.isArray(results)) {
      if (typeof results === "object" && results !== null) {
        // Sometimes AI wraps the array in an object like { "chunks": [...] }
        const possibleArray = Object.values(results).find((v) =>
          Array.isArray(v),
        );
        if (possibleArray) {
          results = possibleArray;
        } else {
          results = [results];
        }
      } else {
        throw new Error("Parsed JSON is neither an object nor an array.");
      }
    }

    // Filter out any that failed internal AI evaluation if the AI was honest
    return (results as (AutoGeneratedChunk & { evaluation?: string })[]).filter(
      (r) => !r.evaluation || r.evaluation.toLowerCase().includes("pass"),
    );
  } catch (e) {
    console.error("Failed to parse AI response:", cleanText);
    throw new Error(
      `AI returned invalid JSON format: ${e instanceof Error ? e.message : "Unknown error"}. Response was: ${cleanText.substring(0, 100)}...`,
    );
  }
}
