import React, { useState, useEffect, useMemo } from 'react';
import { collection, onSnapshot, addDoc } from 'firebase/firestore';
import { db, auth, handleFirestoreError, OperationType } from '../firebase';
import { Resource, Chunk, AISettings, ManualGeneratedChunk } from '../types';
import { generateChunk, generateManualBatch, generateAutoChunks, AutoGeneratedChunk } from '../services/aiService';
import { Wand2, Save, Loader2, Volume2, Sparkles, Settings2, CheckCircle2 } from 'lucide-react';
import { ColorCategory } from '../types';
import { doc, getDoc } from 'firebase/firestore';

export default function MixerTab() {
  const [mode, setMode] = useState<'manual' | 'ai'>('manual');
  const [resources, setResources] = useState<Resource[]>([]);
  const [aiSettings, setAiSettings] = useState<AISettings | undefined>();
  
  // Manual Mode State
  const [selectedIds, setSelectedIds] = useState<Set<string>>(new Set());
  const [iValue, setIValue] = useState<number>(1);
  const [manualQuantity, setManualQuantity] = useState<number>(1);
  const [manualVariationMode, setManualVariationMode] = useState<'paraphrase' | 'scenario' | 'dialogue' | 'mixed'>('mixed');
  const [manualTheme, setManualTheme] = useState('');
  const [generatedManualChunks, setGeneratedManualChunks] = useState<ManualGeneratedChunk[]>([]);
  const [savedManualIndices, setSavedManualIndices] = useState<Set<number>>(new Set());
  
  // AI Mode State
  const [aiTheme, setAiTheme] = useState('');
  const [aiTargetU, setAiTargetU] = useState<number>(30);
  const [aiQuantity, setAiQuantity] = useState<number>(3);
  const [aiSentenceLength, setAiSentenceLength] = useState<'Short' | 'Medium' | 'Long'>('Medium');
  const [aiColors, setAiColors] = useState<ColorCategory[]>(['Green', 'Blue', 'Red', 'Pink']);
  const [aiResults, setAiResults] = useState<AutoGeneratedChunk[]>([]);
  const [savedIndices, setSavedIndices] = useState<Set<number>>(new Set());
  const [editingIndex, setEditingIndex] = useState<number | null>(null);

  const [loading, setLoading] = useState(false);
  const [saving, setSaving] = useState(false);
  const [savingIndex, setSavingIndex] = useState<number | null>(null);
  const [generationProgress, setGenerationProgress] = useState({ current: 0, total: 0 });

  useEffect(() => {
    if (!auth.currentUser) return;

    const unsubscribe = onSnapshot(
      collection(db, `users/${auth.currentUser.uid}/resources`),
      (snapshot) => {
        const resData: Resource[] = [];
        snapshot.forEach((doc) => {
          resData.push({ id: doc.id, ...doc.data() } as Resource);
        });
        setResources(resData);
      },
      (error) => {
        handleFirestoreError(error, OperationType.LIST, `users/${auth.currentUser?.uid}/resources`);
      }
    );

    return () => unsubscribe();
  }, []);

  useEffect(() => {
    if (!auth.currentUser) return;
    const loadSettings = async () => {
      try {
        const docRef = doc(db, `users/${auth.currentUser!.uid}/settings`, 'ai');
        const docSnap = await getDoc(docRef);
        if (docSnap.exists()) {
          setAiSettings(docSnap.data() as AISettings);
        }
      } catch (error) {
        console.error('Error loading AI settings:', error);
      }
    };
    loadSettings();
  }, []);

  const selectedResources = useMemo(() => {
    return resources.filter(r => selectedIds.has(r.id));
  }, [resources, selectedIds]);

  const rTotal = useMemo(() => {
    if (selectedResources.length === 0) return 0;

    const groups: Record<string, number[]> = {};
    selectedResources.forEach(r => {
      if (!groups[r.color]) groups[r.color] = [];
      groups[r.color].push(r.ohm);
    });

    const seriesTotals = Object.values(groups).map(group => 
      group.reduce((sum, ohm) => sum + ohm, 0)
    );

    if (seriesTotals.length === 0) return 0;
    return seriesTotals.reduce((prod, val) => prod * val, 1);
  }, [selectedResources]);

  const uTotal = useMemo(() => {
    return iValue * rTotal;
  }, [iValue, rTotal]);

  const toggleSelection = (id: string) => {
    const newSet = new Set(selectedIds);
    if (newSet.has(id)) {
      newSet.delete(id);
    } else {
      newSet.add(id);
    }
    setSelectedIds(newSet);
  };

  const playAudio = (url?: string | null) => {
    if (!url) return;
    const audio = new Audio(url);
    audio.play();
  };

  const handleGenerate = async () => {
    if (selectedResources.length === 0) return;
    setLoading(true);
    setGeneratedManualChunks([]);
    setSavedManualIndices(new Set());

    try {
      if (manualQuantity <= 1) {
        const chunk = await generateChunk({
          resources: selectedResources,
          iValue,
          sentenceLength: 'Medium',
          theme: manualTheme || undefined,
          settings: aiSettings,
          reviewEnabled: true,
          generateAudio: true,
        });
        setGeneratedManualChunks([chunk]);
      } else {
        const result = await generateManualBatch({
          resources: selectedResources,
          iValue,
          quantity: manualQuantity,
          sentenceLength: 'Medium',
          variationMode: manualVariationMode,
          theme: manualTheme || undefined,
          settings: aiSettings,
          reviewEnabled: true,
          maxAttemptsPerChunk: 3,
          generateAudio: false,
        });
        setGeneratedManualChunks(result.chunks);
        if (result.totalFailed > 0) {
          alert(`Generated ${result.totalSucceeded}/${result.totalRequested} manual chunks. ${result.totalFailed} failed quality checks or retries.`);
        }
      }
    } catch (error) {
      console.error(error);
      alert('Failed to generate manual chunk(s). See console for details.');
    } finally {
      setLoading(false);
    }
  };

  const handleSaveManualChunk = async (chunk: ManualGeneratedChunk, index: number) => {
    if (!auth.currentUser) return;
    setSavingIndex(index);

    try {
      await addDoc(collection(db, `users/${auth.currentUser.uid}/chunks`), {
        ...chunk,
        userId: auth.currentUser.uid,
        createdAt: new Date().toISOString()
      });
      setSavedManualIndices(prev => new Set(prev).add(index));
    } catch (error) {
      handleFirestoreError(error, OperationType.CREATE, `users/${auth.currentUser.uid}/chunks`);
    } finally {
      setSavingIndex(null);
    }
  };

  const handleSaveAllManual = async () => {
    if (!auth.currentUser || generatedManualChunks.length === 0) return;
    setSaving(true);

    try {
      const unsaved = generatedManualChunks.filter((_, idx) => !savedManualIndices.has(idx));
      await Promise.all(unsaved.map(async (chunk) => {
        const originalIdx = generatedManualChunks.indexOf(chunk);
        await addDoc(collection(db, `users/${auth.currentUser!.uid}/chunks`), {
          ...chunk,
          userId: auth.currentUser!.uid,
          createdAt: new Date().toISOString()
        });
        setSavedManualIndices(prev => new Set(prev).add(originalIdx));
      }));
    } catch (error) {
      handleFirestoreError(error, OperationType.CREATE, `users/${auth.currentUser.uid}/chunks`);
    } finally {
      setSaving(false);
    }
  };

  const calculateU = (usedResources: Resource[], i: number) => {
    if (usedResources.length === 0) return 0;
    const groups: Record<string, number[]> = {};
    usedResources.forEach(r => {
      if (!groups[r.color]) groups[r.color] = [];
      groups[r.color].push(r.ohm);
    });
    const seriesTotals = Object.values(groups).map(group => 
      group.reduce((sum, ohm) => sum + ohm, 0)
    );
    const r = seriesTotals.reduce((prod, val) => prod * val, 1);
    return i * r;
  };

  const handleAIGenerate = async () => {
    if (!aiTheme || resources.length === 0) return;
    setLoading(true);
    setAiResults([]);
    setSavedIndices(new Set());
    setGenerationProgress({ current: 0, total: aiQuantity });

    try {
      const results = await generateAutoChunks({
        theme: aiTheme,
        targetU: aiTargetU,
        quantity: aiQuantity,
        sentenceLength: aiSentenceLength,
        colorPreferences: aiColors,
        availableResources: resources,
        settings: aiSettings
      });

      const validatedResults = results.map(res => ({
        ...res,
        iValue: 1,
        uTotal: res.rTotal,
        difficultyLabel: res.rTotal <= 20 ? 'Beginner' : res.rTotal <= 50 ? 'Intermediate' : res.rTotal <= 100 ? 'Advanced' : 'Master',
        audioUrl: null
      }));

      setAiResults(validatedResults);
      setGenerationProgress({ current: validatedResults.length, total: aiQuantity });

      if (validatedResults.length < aiQuantity) {
        alert(`Generated ${validatedResults.length}/${aiQuantity} smart AI chunks. Some candidates failed review or had no suitable resource combo.`);
      }
    } catch (error) {
      console.error(error);
      alert('Failed to auto-generate smart AI chunks. See console for details.');
    } finally {
      setLoading(false);
    }
  };

  const handleSaveAll = async () => {
    if (!auth.currentUser || aiResults.length === 0) return;
    setSaving(true);
    try {
      const unsaved = aiResults.filter((_, idx) => !savedIndices.has(idx));
      await Promise.all(unsaved.map(async (chunk) => {
        const originalIdx = aiResults.indexOf(chunk);
        await addDoc(collection(db, `users/${auth.currentUser!.uid}/chunks`), {
          ...chunk,
          userId: auth.currentUser!.uid,
          createdAt: new Date().toISOString()
        });
        setSavedIndices(prev => new Set(prev).add(originalIdx));
      }));
    } catch (error) {
      handleFirestoreError(error, OperationType.CREATE, `users/${auth.currentUser.uid}/chunks`);
    } finally {
      setSaving(false);
    }
  };

  const handleUpdateResult = (index: number, field: keyof AutoGeneratedChunk, value: any) => {
    setAiResults(prev => {
      const next = [...prev];
      next[index] = { ...next[index], [field]: value };
      return next;
    });
  };

  const handleSaveAIChunk = async (chunk: AutoGeneratedChunk, index: number) => {
    if (!auth.currentUser) return;
    setSavingIndex(index);
    try {
      await addDoc(collection(db, `users/${auth.currentUser.uid}/chunks`), {
        ...chunk,
        userId: auth.currentUser.uid,
        createdAt: new Date().toISOString()
      });
      setSavedIndices(prev => new Set(prev).add(index));
    } catch (error) {
      handleFirestoreError(error, OperationType.CREATE, `users/${auth.currentUser.uid}/chunks`);
    } finally {
      setSavingIndex(null);
    }
  };

  const toggleAiColor = (color: ColorCategory) => {
    setAiColors(prev => 
      prev.includes(color) ? prev.filter(c => c !== color) : [...prev, color]
    );
  };

  return (
    <div className="space-y-6">
      <div className="flex bg-gray-100 p-1 rounded-lg w-fit">
        <button
          onClick={() => setMode('manual')}
          className={`flex items-center px-4 py-2 rounded-md text-sm font-medium transition-all ${mode === 'manual' ? 'bg-white text-red-600 shadow-sm' : 'text-gray-500 hover:text-gray-700'}`}
        >
          <Settings2 className="w-4 h-4 mr-2" /> Manual Mixer
        </button>
        <button
          onClick={() => setMode('ai')}
          className={`flex items-center px-4 py-2 rounded-md text-sm font-medium transition-all ${mode === 'ai' ? 'bg-white text-red-600 shadow-sm' : 'text-gray-500 hover:text-gray-700'}`}
        >
          <Sparkles className="w-4 h-4 mr-2" /> AI Generator
        </button>
      </div>

      {mode === 'manual' ? (
        <div className="grid grid-cols-1 lg:grid-cols-2 gap-6 animate-in fade-in duration-300">
          <div className="space-y-6">
            <div className="bg-white p-6 rounded-xl shadow-sm border border-gray-100">
              <h3 className="text-lg font-medium text-gray-900 mb-4">1. Select Resources</h3>
              <div className="max-h-64 overflow-y-auto border border-gray-200 rounded-md p-2 space-y-2">
                {resources.length === 0 ? (
                  <p className="text-sm text-gray-500 p-2">No resources available. Add some in the Resources tab.</p>
                ) : (
                  resources.map(r => (
                    <label key={r.id} className="flex items-center p-2 hover:bg-gray-50 rounded cursor-pointer">
                      <input
                        type="checkbox"
                        checked={selectedIds.has(r.id)}
                        onChange={() => toggleSelection(r.id)}
                        className="h-4 w-4 text-red-600 focus:ring-red-500 border-gray-300 rounded"
                      />
                      <span className="ml-3 text-sm font-medium text-gray-900">{r.name}</span>
                      <span className="ml-auto text-xs text-gray-500">{r.color} • {r.ohm}Ω</span>
                    </label>
                  ))
                )}
              </div>
            </div>

            <div className="bg-white p-6 rounded-xl shadow-sm border border-gray-100 space-y-4">
              <h3 className="text-lg font-medium text-gray-900 mb-2">2. Set Context & Output</h3>
              <div>
                <label className="block text-sm font-medium text-gray-700 mb-1">Current / MSE (I)</label>
                <input
                  type="number"
                  value={iValue}
                  onChange={(e) => setIValue(Number(e.target.value))}
                  className="w-full rounded-md border-gray-300 shadow-sm focus:border-red-500 focus:ring-red-500 border p-2 text-sm"
                  min="0.1"
                  step="0.1"
                />
              </div>
              <div>
                <label className="block text-sm font-medium text-gray-700 mb-1">Optional Theme</label>
                <input
                  type="text"
                  value={manualTheme}
                  onChange={(e) => setManualTheme(e.target.value)}
                  className="w-full rounded-md border-gray-300 shadow-sm focus:border-red-500 focus:ring-red-500 border p-2 text-sm"
                  placeholder="e.g., Travel, School, Daily Life"
                />
              </div>
              <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                <div>
                  <label className="block text-sm font-medium text-gray-700 mb-1">Number of Sentences</label>
                  <input
                    type="number"
                    value={manualQuantity}
                    onChange={(e) => setManualQuantity(Math.max(1, Math.min(20, Number(e.target.value) || 1)))}
                    className="w-full rounded-md border-gray-300 shadow-sm focus:border-red-500 focus:ring-red-500 border p-2 text-sm"
                    min="1"
                    max="20"
                  />
                </div>
                <div>
                  <label className="block text-sm font-medium text-gray-700 mb-1">Variation Mode</label>
                  <select
                    value={manualVariationMode}
                    onChange={(e) => setManualVariationMode(e.target.value as 'paraphrase' | 'scenario' | 'dialogue' | 'mixed')}
                    className="w-full rounded-md border-gray-300 shadow-sm focus:border-red-500 focus:ring-red-500 border p-2 text-sm"
                  >
                    <option value="mixed">Mixed</option>
                    <option value="paraphrase">Paraphrase</option>
                    <option value="scenario">Scenario</option>
                    <option value="dialogue">Dialogue</option>
                  </select>
                </div>
              </div>
            </div>

            <div className="bg-red-50 p-6 rounded-xl shadow-sm border border-red-100">
              <h3 className="text-lg font-medium text-red-900 mb-4">3. The Semantic Circuit</h3>
              <div className="grid grid-cols-3 gap-4 text-center">
                <div className="bg-white p-3 rounded-lg shadow-sm">
                  <div className="text-xs text-gray-500 font-medium uppercase tracking-wider">Resistance (R)</div>
                  <div className="mt-1 text-2xl font-bold text-gray-900">{rTotal.toFixed(1)}Ω</div>
                </div>
                <div className="bg-white p-3 rounded-lg shadow-sm">
                  <div className="text-xs text-gray-500 font-medium uppercase tracking-wider">Current (I)</div>
                  <div className="mt-1 text-2xl font-bold text-gray-900">{iValue.toFixed(1)}A</div>
                </div>
                <div className="bg-red-600 p-3 rounded-lg shadow-sm text-white">
                  <div className="text-xs text-red-200 font-medium uppercase tracking-wider">Voltage (U)</div>
                  <div className="mt-1 text-2xl font-bold">{uTotal.toFixed(1)}V</div>
                </div>
              </div>
              
              <button
                onClick={handleGenerate}
                disabled={selectedResources.length === 0 || loading}
                className="mt-6 w-full flex justify-center items-center py-3 px-4 border border-transparent rounded-md shadow-sm text-sm font-medium text-white bg-red-600 hover:bg-red-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-red-500 disabled:bg-red-300 disabled:cursor-not-allowed"
              >
                {loading ? (
                  <><Loader2 className="animate-spin -ml-1 mr-2 h-5 w-5" /> Generating...</>
                ) : (
                  <><Wand2 className="-ml-1 mr-2 h-5 w-5" /> {manualQuantity > 1 ? `Generate ${manualQuantity} Chunks` : 'Generate Chunk'}</>
                )}
              </button>
            </div>
          </div>

          <div className="bg-white p-6 rounded-xl shadow-sm border border-gray-100 flex flex-col">
            <div className="flex items-center justify-between mb-4">
              <h3 className="text-lg font-medium text-gray-900">Generated Output</h3>
              {generatedManualChunks.length > 1 && (
                <button
                  onClick={handleSaveAllManual}
                  disabled={saving || savedManualIndices.size === generatedManualChunks.length}
                  className="flex items-center px-4 py-2 bg-green-600 text-white text-sm font-bold rounded-lg hover:bg-green-700 transition-colors disabled:bg-gray-300"
                >
                  {saving ? <Loader2 className="w-4 h-4 mr-2 animate-spin" /> : <Save className="w-4 h-4 mr-2" />}
                  Save All Unsaved
                </button>
              )}
            </div>
            
            {generatedManualChunks.length > 0 ? (
              <div className="space-y-4 overflow-y-auto max-h-[760px] pr-1">
                {generatedManualChunks.map((chunk, idx) => (
                  <div key={idx} className="bg-gray-50 p-5 rounded-xl border border-gray-100 flex flex-col">
                    <div className="flex items-center justify-between mb-3">
                      <span className="text-[10px] font-bold uppercase tracking-widest text-gray-400">Manual Chunk #{idx + 1}</span>
                      <div className="flex items-center gap-2">
                        <span className="px-2 py-0.5 rounded-full text-[10px] font-bold bg-purple-100 text-purple-800">
                          {chunk.difficultyLabel} (U={chunk.uTotal.toFixed(1)})
                        </span>
                        {chunk.audioUrl && (
                          <button 
                            onClick={() => playAudio(chunk.audioUrl)}
                            className="p-1 text-red-600 hover:bg-red-50 rounded-full transition-colors"
                            title="Play Audio"
                          >
                            <Volume2 className="w-4 h-4" />
                          </button>
                        )}
                      </div>
                    </div>

                    <div className="space-y-4 flex-1">
                      <div>
                        <h4 className="text-xs font-semibold text-gray-500 uppercase tracking-wider mb-2">English Sentence</h4>
                        <p className="text-md text-gray-900 font-medium bg-white p-4 rounded-lg border border-gray-200">
                          {chunk.engSentence}
                        </p>
                      </div>

                      <div>
                        <h4 className="text-xs font-semibold text-gray-500 uppercase tracking-wider mb-2">Vietnamese Translation</h4>
                        <p className="text-sm text-gray-700 bg-white p-4 rounded-lg border border-gray-200">
                          {chunk.vieSentence}
                        </p>
                      </div>

                      <div className="grid grid-cols-2 gap-4">
                        <div>
                          <h4 className="text-xs font-semibold text-gray-500 uppercase tracking-wider mb-1">Category</h4>
                          <span className="inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium bg-blue-100 text-blue-800">
                            {chunk.category}
                          </span>
                        </div>
                        <div>
                          <h4 className="text-xs font-semibold text-gray-500 uppercase tracking-wider mb-1">Quality</h4>
                          <span className="inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium bg-green-100 text-green-800">
                            {typeof chunk.qualityScore === 'number' ? `${Math.round(chunk.qualityScore * 100)}%` : 'Reviewed'}
                          </span>
                        </div>
                      </div>

                      <div>
                        <h4 className="text-xs font-semibold text-gray-500 uppercase tracking-wider mb-1">Resources Used</h4>
                        <div className="flex flex-wrap gap-2 mt-2">
                          {chunk.resourcesUsed.map((resource, rIdx) => (
                            <span 
                              key={rIdx} 
                              className={`px-2 py-1 text-xs rounded border font-medium ${
                                resource.color === 'Green' ? 'bg-green-50 text-green-700 border-green-100' :
                                resource.color === 'Blue' ? 'bg-blue-50 text-blue-700 border-blue-100' :
                                resource.color === 'Red' ? 'bg-red-50 text-red-700 border-red-100' :
                                'bg-pink-50 text-pink-700 border-pink-100'
                              }`}
                            >
                              {resource.name}
                            </span>
                          ))}
                        </div>
                      </div>
                    </div>

                    <div className="mt-4 pt-4 border-t border-gray-100">
                      {savedManualIndices.has(idx) ? (
                        <div className="flex items-center justify-center text-green-600 text-sm font-bold py-2">
                          <CheckCircle2 className="w-4 h-4 mr-2" /> Saved to Library
                        </div>
                      ) : (
                        <button
                          onClick={() => handleSaveManualChunk(chunk, idx)}
                          disabled={saving || savingIndex === idx}
                          className="w-full flex justify-center items-center py-2 px-4 border border-gray-200 rounded-md text-xs font-bold text-gray-700 hover:bg-gray-50 transition-colors disabled:opacity-50"
                        >
                          {savingIndex === idx ? (
                            <>
                              <Loader2 className="w-3 h-3 mr-2 animate-spin" /> Saving...
                            </>
                          ) : (
                            <>
                              <Save className="w-3 h-3 mr-2" /> Save this Chunk
                            </>
                          )}
                        </button>
                      )}
                    </div>
                  </div>
                ))}
              </div>
            ) : (
              <div className="flex-1 flex items-center justify-center border-2 border-dashed border-gray-200 rounded-lg bg-gray-50">
                <div className="text-center p-6">
                  <Wand2 className="mx-auto h-12 w-12 text-gray-300" />
                  <p className="mt-2 text-sm text-gray-500">Select resources and click generate to create one or many backend-reviewed chunks.</p>
                </div>
              </div>
            )}
          </div>
        </div>
      ) : (
        <div className="space-y-6 animate-in fade-in duration-300">
          <div className="bg-white p-6 rounded-xl shadow-sm border border-gray-100">
            <h3 className="text-lg font-medium text-gray-900 mb-6 flex items-center">
              <Sparkles className="w-5 h-5 mr-2 text-red-600" /> AI Generation Settings
            </h3>
            
            <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
              <div className="space-y-4">
                <div>
                  <label className="block text-sm font-medium text-gray-700 mb-1">Topic / Theme</label>
                  <input
                    type="text"
                    value={aiTheme}
                    onChange={(e) => setAiTheme(e.target.value)}
                    placeholder="e.g., Business meeting, Travel, Daily life"
                    className="w-full rounded-md border-gray-300 shadow-sm focus:border-red-500 focus:ring-red-500 border p-2 text-sm"
                  />
                </div>
                <div className="grid grid-cols-2 gap-4">
                  <div>
                    <label className="block text-sm font-medium text-gray-700 mb-1">Target Ohm (R)</label>
                    <input
                      type="number"
                      value={aiTargetU}
                      onChange={(e) => setAiTargetU(Number(e.target.value))}
                      className="w-full rounded-md border-gray-300 shadow-sm focus:border-red-500 focus:ring-red-500 border p-2 text-sm"
                      min="5"
                    />
                  </div>
                  <div>
                    <label className="block text-sm font-medium text-gray-700 mb-1">Quantity</label>
                    <input
                      type="number"
                      value={aiQuantity}
                      onChange={(e) => setAiQuantity(Number(e.target.value))}
                      className="w-full rounded-md border-gray-300 shadow-sm focus:border-red-500 focus:ring-red-500 border p-2 text-sm"
                      min="1"
                      max="50"
                    />
                  </div>
                </div>
                <div>
                  <label className="block text-sm font-medium text-gray-700 mb-1">Sentence Length</label>
                  <div className="flex bg-gray-100 p-1 rounded-md">
                    {(['Short', 'Medium', 'Long'] as const).map((len) => (
                      <button
                        key={len}
                        onClick={() => setAiSentenceLength(len)}
                        className={`flex-1 py-1.5 text-xs font-medium rounded transition-all ${
                          aiSentenceLength === len ? 'bg-white text-red-600 shadow-sm' : 'text-gray-500 hover:text-gray-700'
                        }`}
                      >
                        {len}
                      </button>
                    ))}
                  </div>
                </div>
              </div>

              <div>
                <label className="block text-sm font-medium text-gray-700 mb-2">Color Preferences</label>
                <div className="grid grid-cols-2 gap-2">
                  {['Green', 'Blue', 'Red', 'Pink'].map((color) => (
                    <button
                      key={color}
                      onClick={() => toggleAiColor(color as ColorCategory)}
                      className={`flex items-center justify-between px-3 py-2 rounded-md border text-sm transition-all ${
                        aiColors.includes(color as ColorCategory)
                          ? 'bg-red-50 border-red-200 text-red-700 font-medium'
                          : 'bg-white border-gray-200 text-gray-500 hover:bg-gray-50'
                      }`}
                    >
                      {color}
                      {aiColors.includes(color as ColorCategory) && <CheckCircle2 className="w-4 h-4" />}
                    </button>
                  ))}
                </div>
                <p className="mt-2 text-xs text-gray-500">The AI will prioritize resources from these categories.</p>
              </div>
            </div>

            <button
              onClick={handleAIGenerate}
              disabled={!aiTheme || loading || resources.length === 0}
              className="mt-8 w-full flex justify-center items-center py-3 px-4 border border-transparent rounded-md shadow-sm text-sm font-bold text-white bg-red-600 hover:bg-red-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-red-500 disabled:bg-red-300 disabled:cursor-not-allowed transition-all"
            >
              {loading ? (
                <><Loader2 className="animate-spin -ml-1 mr-2 h-5 w-5" /> Generating {generationProgress.current} / {generationProgress.total} Chunks...</>
              ) : (
                <><Sparkles className="-ml-1 mr-2 h-5 w-5" /> Auto-Generate Chunks</>
              )}
            </button>

            {loading && generationProgress.total > 0 && (
              <div className="mt-4 animate-in fade-in duration-300">
                <div className="flex justify-between text-xs font-medium text-gray-500 mb-1.5">
                  <span>Generation Progress</span>
                  <span>{Math.round((generationProgress.current / generationProgress.total) * 100)}%</span>
                </div>
                <div className="w-full bg-gray-100 rounded-full h-2 overflow-hidden">
                  <div 
                    className="bg-red-500 h-2 rounded-full transition-all duration-500 ease-out" 
                    style={{ width: `${(generationProgress.current / generationProgress.total) * 100}%` }}
                  />
                </div>
              </div>
            )}
          </div>

          {aiResults.length > 0 && (
            <div className="space-y-4 animate-in slide-in-from-bottom-4 duration-500">
              <div className="flex items-center justify-between px-2">
                <h3 className="text-lg font-medium text-gray-900">Generated Chunks ({aiResults.length})</h3>
                <button
                  onClick={handleSaveAll}
                  disabled={saving || savedIndices.size === aiResults.length}
                  className="flex items-center px-4 py-2 bg-green-600 text-white text-sm font-bold rounded-lg hover:bg-green-700 transition-colors disabled:bg-gray-300"
                >
                  {saving ? <Loader2 className="w-4 h-4 mr-2 animate-spin" /> : <Save className="w-4 h-4 mr-2" />}
                  Save All Unsaved
                </button>
              </div>
              
              <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                {aiResults.map((res, idx) => (
                  <div key={idx} className="bg-white p-5 rounded-xl shadow-sm border border-gray-100 flex flex-col hover:shadow-md transition-shadow relative group">
                    <div className="flex-1 space-y-4">
                      <div className="flex items-center justify-between">
                        <span className="text-[10px] font-bold uppercase tracking-widest text-gray-400">Chunk #{idx + 1}</span>
                        <div className="flex items-center gap-2">
                          <span className={`px-2 py-0.5 rounded-full text-[10px] font-bold ${
                            res.difficultyLabel === 'Beginner' ? 'bg-green-100 text-green-700' :
                            res.difficultyLabel === 'Intermediate' ? 'bg-blue-100 text-blue-700' :
                            res.difficultyLabel === 'Advanced' ? 'bg-orange-100 text-orange-700' :
                            'bg-red-100 text-red-700'
                          }`}>
                            {res.difficultyLabel} (U={res.uTotal.toFixed(1)})
                          </span>
                          {res.audioUrl && (
                            <button 
                              onClick={() => playAudio(res.audioUrl)}
                              className="p-1 text-red-600 hover:bg-red-50 rounded-full transition-colors"
                            >
                              <Volume2 className="w-4 h-4" />
                            </button>
                          )}
                        </div>
                      </div>
                      
                      <div className="space-y-2">
                        {editingIndex === idx ? (
                          <div className="space-y-2">
                            <textarea
                              value={res.engSentence}
                              onChange={(e) => handleUpdateResult(idx, 'engSentence', e.target.value)}
                              className="w-full text-sm border-gray-200 rounded-md focus:ring-red-500 focus:border-red-500 p-2"
                              rows={2}
                            />
                            <textarea
                              value={res.vieSentence}
                              onChange={(e) => handleUpdateResult(idx, 'vieSentence', e.target.value)}
                              className="w-full text-xs text-gray-500 border-gray-200 rounded-md focus:ring-red-500 focus:border-red-500 p-2"
                              rows={2}
                            />
                            <button 
                              onClick={() => setEditingIndex(null)}
                              className="text-[10px] font-bold text-red-600 hover:underline"
                            >
                              Done Editing
                            </button>
                          </div>
                        ) : (
                          <div onClick={() => setEditingIndex(idx)} className="cursor-text hover:bg-gray-50 p-1 rounded transition-colors">
                            <p className="text-md font-medium text-gray-900 leading-relaxed">{res.engSentence}</p>
                            <p className="text-sm text-gray-500 mt-1 italic">{res.vieSentence}</p>
                          </div>
                        )}
                      </div>

                      <div className="flex flex-wrap gap-1">
                        {res.resourcesUsed.map((resource, rIdx) => (
                          <span 
                            key={rIdx} 
                            className={`px-1.5 py-0.5 text-[10px] rounded border font-medium ${
                              resource.color === 'Green' ? 'bg-green-50 text-green-700 border-green-100' :
                              resource.color === 'Blue' ? 'bg-blue-50 text-blue-700 border-blue-100' :
                              resource.color === 'Red' ? 'bg-red-50 text-red-700 border-red-100' :
                              'bg-pink-50 text-pink-700 border-pink-100'
                            }`}
                          >
                            {resource.name}
                          </span>
                        ))}
                      </div>
                    </div>

                    <div className="mt-4 pt-4 border-t border-gray-50">
                      {savedIndices.has(idx) ? (
                        <div className="flex items-center justify-center text-green-600 text-sm font-bold py-2">
                          <CheckCircle2 className="w-4 h-4 mr-2" /> Saved to Library
                        </div>
                      ) : (
                        <button
                          onClick={() => handleSaveAIChunk(res, idx)}
                          disabled={saving || savingIndex === idx}
                          className="w-full flex justify-center items-center py-2 px-4 border border-gray-200 rounded-md text-xs font-bold text-gray-700 hover:bg-gray-50 transition-colors disabled:opacity-50"
                        >
                          {savingIndex === idx ? (
                            <>
                              <Loader2 className="w-3 h-3 mr-2 animate-spin" /> Saving...
                            </>
                          ) : (
                            <>
                              <Save className="w-3 h-3 mr-2" /> Save this Chunk
                            </>
                          )}
                        </button>
                      )}
                    </div>
                  </div>
                ))}
              </div>
            </div>
          )}
        </div>
      )}
    </div>
  );
}
